import type { ArchitectureLabDefinition } from "./types";

export const demoArchitectureLab: ArchitectureLabDefinition = {
  id: "demo-enterprise-readiness-lab",
  title: "Turn a prototype into an enterprise-ready system",
  duration: 12,
  difficulty: "guided",
  scenario: {
    id: "prototype-to-enterprise",
    title: "A promising assistant must enter production",
    description: "A team has demonstrated an AI assistant that answers questions from a small document set. The organization now wants to make it available as a dependable enterprise service.",
    context: "Demo content only — this validates the reusable lab framework and is not production Lesson 1 content.",
  },
  requirements: [
    { id: "scale", statement: "Support many enterprise users." },
    { id: "confidentiality", statement: "Protect confidential information." },
    { id: "integration", statement: "Connect with authoritative enterprise systems." },
    { id: "operations", statement: "Operate reliably in production." },
  ],
  startingArchitecture: ["User", "Web Application", "LLM", "Documents"],
  capabilityMatching: {
    id: "core-capability-matching",
    title: "Match each capability to its architectural role",
    introduction: "Connect the six core capabilities with the responsibilities they contribute before you use them in the guided builder.",
    prompts: [
      { id: "match-identity", label: "Identity & Access", context: "Access boundary", matchingItemId: "role-identity" },
      { id: "match-retrieval", label: "RAG / Retrieval", context: "Knowledge grounding", matchingItemId: "role-retrieval" },
      { id: "match-integration", label: "Enterprise Integration", context: "System connection", matchingItemId: "role-integration" },
      { id: "match-security", label: "Security & Guardrails", context: "Protection and constraints", matchingItemId: "role-security" },
      { id: "match-observability", label: "Observability", context: "Operational visibility", matchingItemId: "role-observability" },
      { id: "match-governance", label: "Governance", context: "Policy and accountability", matchingItemId: "role-governance" },
    ],
    items: [
      { id: "role-governance", description: "Define policy, accountability, auditability and risk controls." },
      { id: "role-retrieval", description: "Ground AI responses using approved enterprise knowledge." },
      { id: "role-observability", description: "Monitor quality, latency, failures, usage and operational health." },
      { id: "role-identity", description: "Verify users and control what information or actions they are permitted to access." },
      { id: "role-integration", description: "Connect the AI solution with authoritative enterprise systems and APIs." },
      { id: "role-security", description: "Protect sensitive information and constrain unsafe AI behavior." },
    ],
  },
  slots: [
    { id: "identity-slot", label: "Identity & access", description: "Control who enters the experience and what they may access.", zone: "flow", placeholder: "Choose an access capability" },
    { id: "ai-slot", label: "AI & retrieval", description: "Ground the assistant in approved enterprise knowledge.", zone: "flow", placeholder: "Choose an AI or retrieval capability" },
    { id: "data-slot", label: "Enterprise data", description: "Provide governed information for the assistant.", zone: "flow", placeholder: "Choose a data capability" },
    { id: "integration-slot", label: "Integration", description: "Connect the assistant to authoritative systems.", zone: "flow", placeholder: "Choose an integration capability" },
    { id: "control-slot", label: "Security & governance", description: "Apply cross-cutting protection and decision controls.", zone: "cross-cutting", placeholder: "Choose a cross-cutting capability" },
    { id: "operations-slot", label: "Operations foundation", description: "Make quality, failures, usage and cost observable.", zone: "foundation", placeholder: "Choose an operational capability" },
  ],
  availableComponents: [
    { id: "identity", domainId: "security", label: "Identity & Access", description: "Verify users and enforce access.", capability: "identity", purpose: "Verify users and control what they are allowed to access.", compatibleSlotIds: ["identity-slot"] },
    { id: "retrieval", domainId: "ai", label: "RAG / Retrieval", description: "Retrieve approved knowledge.", capability: "retrieval", purpose: "Ground AI responses in approved enterprise knowledge.", compatibleSlotIds: ["ai-slot"] },
    { id: "enterprise-data", domainId: "data", label: "Enterprise Data", description: "Provide governed information.", capability: "enterprise-data", purpose: "Provide governed business information.", compatibleSlotIds: ["data-slot"] },
    { id: "integration", domainId: "integration", label: "Integration", description: "Connect authoritative systems.", capability: "integration", purpose: "Connect AI with authoritative enterprise systems.", compatibleSlotIds: ["integration-slot"] },
    { id: "guardrails", domainId: "security", label: "Security & Guardrails", description: "Protect data and constrain behavior.", capability: "security", crossCutting: true, purpose: "Protect data and constrain unsafe AI behavior.", compatibleSlotIds: ["control-slot"] },
    { id: "governance", domainId: "governance", label: "Governance", description: "Define accountable controls.", capability: "governance", crossCutting: true, purpose: "Apply policy, accountability and lifecycle controls.", compatibleSlotIds: ["control-slot"] },
    { id: "observability", domainId: "operations", label: "Observability", description: "Monitor the production system.", capability: "observability", purpose: "Monitor quality, latency, failures and usage.", compatibleSlotIds: ["operations-slot"] },
    { id: "operations-cost", domainId: "operations", label: "Operations & Cost", description: "Operate and manage consumption.", capability: "operations", purpose: "Manage reliability, capacity and cost as usage grows.", compatibleSlotIds: ["operations-slot"] },
    { id: "larger-model", domainId: "ai", label: "Larger LLM", description: "Increase model capacity.", capability: "larger-model", purpose: "Increase model capacity without resolving wider enterprise controls.", compatibleSlotIds: ["ai-slot"] },
    { id: "prompt-templates", domainId: "ai", label: "More Prompt Templates", description: "Standardize more prompts.", capability: "prompt-templates", purpose: "Standardize prompts without resolving wider enterprise gaps.", compatibleSlotIds: ["ai-slot"] },
  ],
  reviewRules: [
    { id: "identity-rule", type: "required-capability", capabilityIds: ["identity"], strength: "You introduced identity before allowing access to employee-specific information.", gap: "The design does not yet establish who may access confidential information.", nextQuestion: "How will authorization follow the user into retrieval and downstream systems?" },
    { id: "retrieval-rule", type: "recommended-capability", capabilityIds: ["retrieval"], strength: "Retrieval grounds responses in approved enterprise knowledge.", consideration: "Consider how the assistant will ground answers in current, approved information.", nextQuestion: "How will retrieval filter content to the user's authorization context?" },
    { id: "data-rule", type: "recommended-capability", capabilityIds: ["enterprise-data"], strength: "The design recognizes governed enterprise data as a distinct capability.", consideration: "Consider where authoritative, governed information enters the architecture." },
    { id: "integration-rule", type: "relationship-consideration", capabilityIds: ["integration"], strength: "You included a controlled path to authoritative enterprise systems.", gap: "The design does not yet include a controlled integration path to an authoritative enterprise system.", nextQuestion: "Which contracts, failure paths and permissions should the integration enforce?" },
    { id: "control-rule", type: "cross-cutting-capability", capabilityIds: ["security", "governance"], strength: "You treated protection or governance as a cross-cutting architecture concern.", gap: "Cross-cutting security or governance controls are not yet represented.", nextQuestion: "Who owns policy decisions and evidence when the assistant's behavior changes?" },
    { id: "operations-rule", type: "operational-capability", capabilityIds: ["observability", "operations"], strength: "The architecture includes a foundation for production visibility and operation.", consideration: "How will the team monitor failures, latency and cost as usage grows?", gap: "The production operating model is not yet visible in the design." },
    { id: "larger-model-rule", type: "distractor-selected", capabilityIds: ["larger-model"], consideration: "A larger model may improve some responses, but it does not by itself address identity, integration, governance or production operation.", nextQuestion: "Which enterprise requirement does additional model capacity directly satisfy?" },
    { id: "prompts-rule", type: "distractor-selected", capabilityIds: ["prompt-templates"], consideration: "Prompt templates can improve consistency, while the core access, data and operating concerns still need architectural treatment.", nextQuestion: "What controls remain necessary outside the prompt layer?" },
  ],
  referenceArchitecture: {
    title: "One possible enterprise architecture",
    summary: "This approach combines a governed knowledge path with explicit access, integration, cross-cutting controls and an operational foundation. Another valid design may distribute these responsibilities differently.",
    placements: [
      { slotId: "identity-slot", componentId: "identity" }, { slotId: "ai-slot", componentId: "retrieval" }, { slotId: "data-slot", componentId: "enterprise-data" }, { slotId: "integration-slot", componentId: "integration" }, { slotId: "control-slot", componentId: "guardrails" }, { slotId: "operations-slot", componentId: "observability" },
    ],
    decisions: ["Carry user authorization into retrieval and integration.", "Keep authoritative data and system access behind governed interfaces.", "Observe quality, latency, failures, usage and cost as one operating concern."],
  },
  finalChallenge: {
    id: "write-actions",
    prompt: "The business now wants the AI assistant to update enterprise records, not only answer questions. What changes architecturally?",
    options: [
      { id: "direct-write", label: "Let the model write directly to the database after generating a confident answer.", feedback: "Confidence is not an authorization or transaction control. Consider how writes are constrained, validated and audited." },
      { id: "more-prompts", label: "Add prompt templates that tell the model to update records carefully.", feedback: "Prompts can guide behavior but cannot provide transaction integrity, permissions or durable audit evidence." },
      { id: "controlled-tools", label: "Introduce controlled tool/API execution with stronger authorization, validation, audit logging and appropriate human or system controls.", feedback: "Strong decision. Moving from answers to actions introduces transaction, authorization, validation and accountability concerns that need explicit architecture.", isStrongest: true },
      { id: "bigger-model", label: "Use a larger model so record updates are more accurate.", feedback: "Model capability may affect interpretation, but enterprise writes still require controlled execution, validation and auditability." },
    ],
  },
  completionCriteria: { minimumPlacements: 4, requiredSlotIds: ["identity-slot", "integration-slot"] },
};
