import type { ArchitectureLabDefinition } from "./types";

export const productionLesson1ArchitectureLab: ArchitectureLabDefinition = {
  id: "lesson-1-architecture-lab-01",
  title: "Design Your First Enterprise AI Architecture",
  duration: 20,
  difficulty: "guided",
  experienceModel: "production-guided-lab",
  scenario: {
    id: "hr-employee-assistant",
    title: "AI-powered Employee Assistant",
    description: "Turn an HR business request into a high-level architecture that could realistically operate inside an enterprise.",
    context: "Vendor-neutral · Guided Foundation Lab · Approximately 15–25 minutes",
  },
  requirements: [
    { id: "users", statement: "Approximately 10,000 employees" },
    { id: "identity", statement: "Existing enterprise identity" },
    { id: "knowledge", statement: "HR policies and internal documents" },
    { id: "live-data", statement: "Current employee leave information" },
    { id: "sensitivity", statement: "Employee-specific information" },
    { id: "availability", statement: "Business-critical employee service" },
    { id: "rollout", statement: "Controlled production deployment" },
  ],
  startingArchitecture: ["Employee", "Employee Portal", "Application / Orchestrator"],
  capabilityMatching: { id: "production-information-classification", title: "Classify the information", introduction: "Separate enterprise knowledge, live system data, and identity context.", prompts: [], items: [] },
  slots: [
    { id: "user", label: "Employee / User", description: "The person using the workload.", zone: "flow", placeholder: "Choose the user capability" },
    { id: "experience", label: "Experience Layer", description: "The employee-facing channel.", zone: "flow", placeholder: "Choose the experience capability" },
    { id: "application", label: "Application / Orchestration", description: "Coordinates workflow and business logic.", zone: "flow", placeholder: "Choose the application capability" },
    { id: "ai", label: "AI / Intelligence", description: "Provides appropriate language intelligence.", zone: "flow", placeholder: "Choose the intelligence capability" },
    { id: "knowledge", label: "Enterprise Data / Knowledge", description: "Provides approved policy knowledge.", zone: "flow", placeholder: "Choose the knowledge capability" },
    { id: "integration", label: "Integration", description: "Connects controlled enterprise interfaces.", zone: "flow", placeholder: "Choose the integration capability" },
    { id: "systems", label: "Enterprise Systems", description: "Holds current authoritative HR facts.", zone: "flow", placeholder: "Choose the enterprise system" },
    { id: "identity-controls", label: "Identity & Access", description: "Establishes identity and access boundaries.", zone: "cross-cutting", placeholder: "Choose identity and access" },
    { id: "security", label: "Security & Governance", description: "Applies protection and governance across the workload.", zone: "cross-cutting", placeholder: "Choose security controls" },
    { id: "operations", label: "Observability & Operations", description: "Supports reliable and economical operation.", zone: "foundation", placeholder: "Choose operational capability" },
  ],
  availableComponents: [
    { id: "employee", domainId: "users", label: "Employee", description: "Uses the HR assistant.", capability: "business-alignment", purpose: "Represents the employee using the workload.", compatibleSlotIds: ["user"] },
    { id: "employee-portal", domainId: "applications", label: "Employee Portal", description: "Provides the employee experience.", capability: "business-alignment", purpose: "Provides an accessible employee-facing channel.", compatibleSlotIds: ["experience"] },
    { id: "orchestrator", domainId: "applications", label: "Application / Orchestrator", description: "Coordinates the workload.", capability: "application", purpose: "Coordinates workflow, business logic, data access and AI use.", compatibleSlotIds: ["application"] },
    { id: "ai-model", domainId: "ai", label: "LLM / AI Model", description: "Supports language interaction.", capability: "ai", purpose: "Interprets or generates language where useful.", compatibleSlotIds: ["ai"] },
    { id: "retrieval", domainId: "ai", label: "Retrieval / Knowledge Service", description: "Finds approved knowledge.", capability: "knowledge", purpose: "Finds relevant approved enterprise knowledge.", compatibleSlotIds: ["knowledge"] },
    { id: "policy-repository", domainId: "data", label: "HR Policy Repository", description: "Stores approved policies.", capability: "knowledge", purpose: "Provides governed HR policy documents to the knowledge path.", compatibleSlotIds: ["knowledge"] },
    { id: "hr-api", domainId: "integration", label: "HR System API", description: "Provides controlled current access.", capability: "integration", purpose: "Provides controlled access to current employee information.", compatibleSlotIds: ["integration"] },
    { id: "hr-system", domainId: "systems", label: "HR System of Record", description: "Holds authoritative HR data.", capability: "authoritative-data", purpose: "Provides current authoritative employee information.", compatibleSlotIds: ["systems"] },
    { id: "enterprise-identity", domainId: "security", label: "Enterprise Identity", description: "Establishes user identity.", capability: "identity", purpose: "Establishes the user’s enterprise identity.", compatibleSlotIds: ["identity-controls"] },
    { id: "authorization", domainId: "security", label: "Authorization Controls", description: "Enforces access boundaries.", capability: "security", purpose: "Controls what an identity is permitted to access or do.", compatibleSlotIds: ["security"] },
    { id: "monitoring", domainId: "operations", label: "Logging / Monitoring", description: "Provides operational visibility.", capability: "operations", purpose: "Makes quality, reliability, usage, failures and cost observable.", compatibleSlotIds: ["operations"] },
  ],
  reviewRules: [
    { id: "business", type: "required-capability", capabilityIds: ["business-alignment"], strength: "Business use cases and users were identified.", gap: "Architectural gap: the user and business experience need clearer representation." },
    { id: "identity", type: "required-capability", capabilityIds: ["identity"], strength: "Enterprise identity and access boundaries were considered.", gap: "Architectural gap: enterprise identity is not represented." },
    { id: "knowledge", type: "recommended-capability", capabilityIds: ["knowledge"], strength: "Policy knowledge was separated from current transactional data.", consideration: "Consider how approved policy knowledge enters the workload." },
    { id: "integration", type: "required-capability", capabilityIds: ["integration", "authoritative-data"], strength: "Authoritative HR information is accessed through controlled integration.", gap: "Architectural gap: current HR information needs a controlled authoritative path." },
    { id: "security", type: "cross-cutting-capability", capabilityIds: ["security"], strength: "Cross-cutting security and governance concerns were considered.", gap: "Architectural gap: access enforcement and governance need representation." },
    { id: "operations", type: "operational-capability", capabilityIds: ["operations"], strength: "Monitoring, reliability and cost were included.", consideration: "Operational consideration: make reliability, usage, failures and cost visible." },
  ],
  referenceArchitecture: {
    title: "One Defensible Architecture",
    summary: "This is one defensible high-level design, not the only possible architecture. Technology choices and detailed topology depend on organizational requirements, constraints, risks and operating environment.",
    placements: [
      { slotId: "user", componentId: "employee" }, { slotId: "experience", componentId: "employee-portal" }, { slotId: "application", componentId: "orchestrator" }, { slotId: "ai", componentId: "ai-model" }, { slotId: "knowledge", componentId: "retrieval" }, { slotId: "integration", componentId: "hr-api" }, { slotId: "systems", componentId: "hr-system" }, { slotId: "identity-controls", componentId: "enterprise-identity" }, { slotId: "security", componentId: "authorization" }, { slotId: "operations", componentId: "monitoring" },
    ],
    decisions: ["Separate approved policy knowledge from current employee-specific HR data.", "Carry identity and authorization across knowledge and system access.", "Use controlled integration for authoritative HR facts and observe the complete workload."],
  },
  finalChallenge: { id: "production-lab-placeholder", prompt: "Production lab stages provide the applied challenge.", options: [] },
  completionCriteria: { minimumPlacements: 8, requiredSlotIds: ["identity-controls", "integration", "systems", "operations"] },
};
