"use client";

import { EnterpriseArchitectureExplorer } from "@/modules/architecture-explorer/components/enterprise-architecture-explorer";
import { enterpriseAiArchitecture } from "@/modules/architecture-explorer/enterprise-ai-example";
import { productionLesson1ArchitectureLab } from "@/modules/architecture-lab/production-lesson-1-lab";
import type { ArchitectureLabState } from "@/modules/architecture-lab/types";
import type { ArchitectureExplorationExperienceDefinition, ArchitectureExplorationState } from "../types";

export function ArchitectureExplorationExperience({ experience, state, labState, onChange }: { experience: ArchitectureExplorationExperienceDefinition; state: ArchitectureExplorationState; labState?: ArchitectureLabState; onChange: (state: ArchitectureExplorationState) => void }) {
  const usesLearnerArchitecture = Boolean(labState?.completed && labState.placements.length);
  const placements = usesLearnerArchitecture ? labState!.placements : productionLesson1ArchitectureLab.referenceArchitecture.placements;
  const componentLabels = placements.map((placement) => productionLesson1ArchitectureLab.availableComponents.find((component) => component.id === placement.componentId)?.label).filter((label): label is string => Boolean(label));
  const selectedNode = enterpriseAiArchitecture.nodes.find((node) => node.id === state.selectedDomainId);
  const selectedDomain = experience.domains.find((domain) => domain.explorerTargetId === state.selectedDomainId) ?? experience.domains.find((domain) => enterpriseAiArchitecture.nodes.find((node) => node.id === domain.explorerTargetId)?.domainId === selectedNode?.domainId);
  const scenariosReady = experience.changeScenarios.every((scenario) => Boolean(state.scenarioSelections[scenario.id]?.length));
  const ready = scenariosReady && Boolean(state.reflectionResponse.trim());
  const toggleScenarioConcern = (scenarioId: string, concernId: string) => {
    const selected = state.scenarioSelections[scenarioId] ?? [];
    onChange({ ...state, scenarioSelections: { ...state.scenarioSelections, [scenarioId]: selected.includes(concernId) ? selected.filter((id) => id !== concernId) : [...selected, concernId] } });
  };

  if (state.completed) return <article className="experience-surface production-experience architecture-exploration-experience"><header className="experience-heading"><p className="eyebrow">{experience.eyebrow} · Complete</p><h1 tabIndex={-1}>{experience.title}</h1></header><section className="exploration-complete" role="status"><p>{experience.completion[0]}</p><ul><li>{experience.completion[1]}</li><li>{experience.completion[2]}</li></ul><h2>Continue to the Knowledge Check.</h2><p>Apply your reasoning across five short architecture scenarios.</p></section></article>;

  return <article className="experience-surface production-experience architecture-exploration-experience"><header className="experience-heading"><p className="eyebrow">{experience.eyebrow}</p><h1 tabIndex={-1}>{experience.title}</h1><p className="exploration-subtitle">{experience.summary}</p></header>
    <section className="exploration-opening">{experience.opening.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<div className="architecture-source-note"><strong>{usesLearnerArchitecture ? "Your Architecture Lab 01 design" : "Reference architecture fallback"}</strong><p>{usesLearnerArchitecture ? "Your completed lab selections provide the design context for this exploration." : "No completed lab design is available in this session, so one defensible reference architecture is shown without interruption."}</p><ul aria-label="Architecture components in context">{componentLabels.map((label) => <li key={label}>{label}</li>)}</ul></div></section>
    <section className="hr-architecture-explorer" aria-labelledby="explore-domains-title"><div className="exploration-section-heading"><p className="eyebrow">HR Assistant architecture</p><h2 id="explore-domains-title">Select a domain to trace its relationships</h2><p>Related pathways become prominent while the connected system remains visible.</p></div><EnterpriseArchitectureExplorer selectedDomainId={state.selectedDomainId} onSelectedDomainChange={(selectedDomainId) => onChange({ ...state, selectedDomainId })} />{selectedDomain && <aside className="hr-domain-context" aria-live="polite" aria-atomic="true"><p className="eyebrow">{selectedDomain.title}</p><h3>{selectedDomain.explanation}</h3><p>In this HR Assistant, connect this domain to:</p><ul>{selectedDomain.connections.map((connection) => <li key={connection}>{connection}</li>)}</ul>{selectedDomain.qualification && <p className="domain-qualification">{selectedDomain.qualification}</p>}<blockquote>{selectedDomain.architectQuestion}</blockquote></aside>}</section>
    <section className="change-scenarios" aria-labelledby="change-scenarios-title"><div className="exploration-section-heading"><p className="eyebrow">What would change if…</p><h2 id="change-scenarios-title">Revisit the architecture assumptions</h2><p>Select the concerns you would revisit. These scenarios are not scored.</p></div>{experience.changeScenarios.map((scenario, index) => { const selected = state.scenarioSelections[scenario.id] ?? []; return <article className="change-scenario" key={scenario.id}><p className="scenario-number">Scenario {index + 1}</p><h3>{scenario.prompt}</h3><fieldset><legend>Select relevant concerns</legend><div>{scenario.concerns.map((concern) => <label className={selected.includes(concern.id) ? "is-selected" : ""} key={concern.id}><input type="checkbox" checked={selected.includes(concern.id)} onChange={() => toggleScenarioConcern(scenario.id, concern.id)} /><span>{concern.label}</span></label>)}</div></fieldset>{selected.length > 0 && <div className="scenario-feedback" role="status"><p>{scenario.feedback}</p>{scenario.qualification && <p>{scenario.qualification}</p>}</div>}</article>; })}</section>
    <aside className="exploration-insight"><p className="eyebrow">Architect Insight</p><blockquote>{experience.insight}</blockquote></aside>
    <section className="exploration-reflection"><label htmlFor={`${experience.id}-reflection`}><span className="eyebrow">Reflection</span><strong>{experience.reflectionPrompt}</strong><small>{experience.reflectionHelper}</small></label><textarea id={`${experience.id}-reflection`} rows={5} value={state.reflectionResponse} onChange={(event) => onChange({ ...state, reflectionResponse: event.target.value })} /><button className="primary-button" type="button" disabled={!ready} onClick={() => onChange({ ...state, completed: true })}>Continue to Knowledge Check</button>{!ready && <p>Explore each change scenario and add a short reflection to continue.</p>}</section>
  </article>;
}
