"use client";

import type { ArchitectThinkingExperienceDefinition, ArchitectThinkingState, DecisionOption } from "../types";
import { ArchitectingAiIcon } from "@/components/icons";

type Choice = DecisionOption & { consequence: string; rationale?: string; tradeoff?: string; risk?: string; mitigation?: string; indicators?: Partial<Record<Indicator, number>> };
type Indicator = "Cost" | "Complexity" | "Security" | "Reliability" | "Performance" | "Time-to-market";

const classificationItems = [
  { id: "approved-policy", text: "Employees need policy answers grounded in approved HR information.", answer: "requirement" },
  { id: "vector-database", text: "We must use a vector database.", answer: "solution" },
  { id: "ticket-latency", text: "Current ticket status must be returned within an acceptable response time.", answer: "requirement" },
  { id: "largest-model", text: "We should use the largest available LLM.", answer: "solution" },
] as const;

const habits = [
  { title: "Start with outcomes, not technology", body: "Establish the business outcome, beneficiaries, success measures, and impact of failure before discussing models, platforms, or tools.", questions: ["What business problem are we solving?", "Who benefits?", "How will success be measured?", "What happens if the solution is unavailable or incorrect?"] },
  { title: "Separate requirements from solutions", body: "A stakeholder may present a preferred technology as a requirement. Preserve the underlying need before committing to an implementation." },
  { title: "Identify constraints early", body: "Security, privacy, latency, availability, integration, cost, policy, existing technology, operating skills, and time-to-market can eliminate an otherwise attractive design." },
  { title: "Reason in trade-offs", body: "Higher resilience may increase cost or complexity; real-time integration can strengthen source-system dependency; larger models may increase cost or latency. These relationships depend on the workload." },
  { title: "Design for change", body: "Requirements, providers, data, regulations, scale, integrations, and operating constraints change. Avoid unnecessary coupling, while recognizing that complete vendor independence is not always achievable." },
];

const scenarioReveals: { id: string; label: string; requirement: string; prompt: string; options: Choice[] }[] = [
  { id: "knowledge", label: "Knowledge", requirement: "Answers about IT policies must be grounded in approved internal information.", prompt: "What should you clarify before choosing the technical approach?", options: [
    { id: "knowledge-context", label: "Clarify source ownership, freshness, access restrictions, update lifecycle, and expected answer quality.", consequence: "This preserves the requirement and establishes the conditions an approach must satisfy." },
    { id: "knowledge-rag", label: "Commit to RAG immediately because grounding always requires it.", consequence: "RAG may be suitable, but selecting it before understanding the information lifecycle closes the decision too early." },
    { id: "knowledge-model", label: "Select a larger model and rely on its internal knowledge.", consequence: "Model knowledge does not establish ownership, approval, freshness, or enterprise access controls." },
  ]},
  { id: "live-data", label: "Live data", requirement: "Employees must see the current status of their own service tickets.", prompt: "What architectural concern does this introduce?", options: [
    { id: "live-authority", label: "Authoritative current data through controlled ITSM integration.", consequence: "The design must define freshness, authorization, dependency behavior, and the appropriate system-of-record interface." },
    { id: "live-index", label: "Put all ticket records in the policy knowledge index.", consequence: "An index may not meet current-data, authorization, or transactional lifecycle needs." },
  ]},
  { id: "confidentiality", label: "Confidentiality", requirement: "Some service tickets contain confidential information.", prompt: "What becomes architecturally important?", options: [
    { id: "confidential-controls", label: "Identity, authorization, data-access enforcement, sensitive-data handling, and auditability.", consequence: "These controls must operate across the request path, not as a final downstream security step." },
    { id: "confidential-prompt", label: "Add a prompt telling the model not to reveal confidential data.", consequence: "Prompt guidance alone cannot enforce enterprise authorization and data access." },
  ]},
  { id: "availability", label: "Availability", requirement: "The service is expected to support employees 24×7.", prompt: "What questions should the architect now ask?", options: [
    { id: "availability-questions", label: "Clarify service levels, dependency availability, failure behavior, resilience, support, and recovery expectations.", consequence: "A usage expectation informs the design, but does not automatically prescribe active-active deployment." },
    { id: "availability-maximum", label: "Make every dependency maximally redundant.", consequence: "Maximum redundancy may not be justified for every capability and can add significant cost and complexity." },
  ]},
  { id: "cost", label: "Cost", requirement: "Finance wants the first release delivered within a constrained operating budget.", prompt: "What changes?", options: [
    { id: "cost-constraint", label: "Treat cost as an explicit constraint alongside quality, risk, and business criticality.", consequence: "The architecture position must now explain where spend creates sufficient business value and risk reduction." },
    { id: "cost-ignore", label: "Ignore cost until after the production architecture is complete.", consequence: "Cost affects feasible architecture choices and should be reasoned about early." },
  ]},
];

const tradeoffDecisions: { id: string; title: string; context: string; dimensions: string[]; options: Choice[] }[] = [
  { id: "knowledge-approach", title: "Knowledge approach", context: "IT policy information changes periodically and answers should be grounded in approved enterprise information.", dimensions: ["Grounding", "Operational effort", "Flexibility", "Freshness"], options: [
    { id: "model-knowledge", label: "Rely primarily on model knowledge", consequence: "Fast to start, with weaker enterprise grounding and freshness assurance.", rationale: "Minimizes retrieval infrastructure for low-risk content.", tradeoff: "Accepts reduced control over grounding and freshness.", risk: "Answers may diverge from approved policy.", mitigation: "Limit scope and clearly route authoritative questions elsewhere.", indicators: { Cost: -1, Complexity: -1, Security: -1, "Time-to-market": 1 } },
    { id: "governed-retrieval", label: "Use governed enterprise knowledge retrieval", consequence: "Improves grounding and update control, while introducing ingestion and operational work.", rationale: "Connects answers to approved information with a governed lifecycle.", tradeoff: "Accepts additional implementation and operating complexity.", risk: "Stale or incorrectly permissioned indexed content.", mitigation: "Define ownership, refresh, access, and quality controls.", indicators: { Cost: 1, Complexity: 1, Security: 1, Reliability: 1 } },
    { id: "curated-static", label: "Use curated static responses for selected questions", consequence: "Strong control for a narrow scope, with limited flexibility and higher editorial effort.", rationale: "Prioritizes predictable answers for a bounded question set.", tradeoff: "Accepts limited coverage and manual maintenance.", risk: "Responses may lag policy changes.", mitigation: "Assign owners and review dates for curated answers.", indicators: { Cost: 0, Complexity: 0, Security: 1, "Time-to-market": -1 } },
  ]},
  { id: "ticket-data", title: "Current ticket data", context: "Users need the current status of their own tickets.", dimensions: ["Freshness", "Dependency", "Complexity", "Performance"], options: [
    { id: "live-itsm", label: "Controlled live ITSM API access", consequence: "Maximizes freshness but creates a runtime dependency on ITSM availability and latency.", rationale: "Retrieves current ticket information from the authoritative source.", tradeoff: "Accepts runtime dependency and integration complexity.", risk: "ITSM outage may affect ticket-status capability.", mitigation: "Consider graceful degradation, caching, or clear partial-service behavior.", indicators: { Complexity: 1, Reliability: -1, Performance: -1, Security: 1 } },
    { id: "ticket-cache", label: "Periodically replicated or cached ticket information", consequence: "Can improve response resilience and performance while accepting bounded staleness.", rationale: "Balances current-enough information against dependency and latency needs.", tradeoff: "Accepts that displayed status may not be fully current.", risk: "A user may see stale ticket status.", mitigation: "Display freshness and tune refresh to the workload requirement.", indicators: { Complexity: 1, Reliability: 1, Performance: 1, Cost: 1 } },
    { id: "ticket-index", label: "Include ticket information in the knowledge index", consequence: "May simplify one retrieval path but creates concerns for transactional freshness and fine-grained access.", rationale: "Uses the existing retrieval capability for ticket context.", tradeoff: "Accepts a weaker fit for current employee-specific data.", risk: "Stale or incorrectly exposed ticket information.", mitigation: "Restrict this approach to cases whose freshness and access needs it can demonstrably meet.", indicators: { Security: -1, Reliability: -1, "Time-to-market": 1 } },
  ]},
  { id: "model-strategy", title: "Model strategy", context: "The workload includes classification, routing, policy Q&A, and response generation.", dimensions: ["Complexity", "Cost", "Latency", "Operational simplicity"], options: [
    { id: "single-model", label: "Use one capable model for all AI tasks", consequence: "Operationally simpler, but may over-provision capability and cost for some tasks.", rationale: "Prioritizes a simple initial operating model.", tradeoff: "Accepts possible cost and latency inefficiency.", risk: "The single model may be poorly matched to a task.", mitigation: "Measure task outcomes and split services only where justified.", indicators: { Complexity: -1, Cost: 1, "Time-to-market": 1 } },
    { id: "task-models", label: "Use task-appropriate models or services where justified", consequence: "Can improve task fit and economics, while adding routing and operational complexity.", rationale: "Matches capability to workload needs where evidence supports it.", tradeoff: "Accepts a more complex model estate.", risk: "Routing and evaluation become harder to operate.", mitigation: "Introduce specialization incrementally with clear evaluation criteria.", indicators: { Complexity: 1, Cost: -1, Performance: 1, "Time-to-market": -1 } },
  ]},
  { id: "availability", title: "Availability", context: "Employees expect 24×7 access, but not every capability has an identical stated availability need.", dimensions: ["Reliability", "Cost", "Complexity", "Business criticality"], options: [
    { id: "simple-recovery", label: "Simple deployment with documented recovery", consequence: "Controls cost and complexity but accepts longer disruption during failures.", rationale: "Aligns a first release to modest criticality and recovery expectations.", tradeoff: "Accepts lower resilience.", risk: "The complete service may be unavailable during recovery.", mitigation: "Document recovery, communicate service expectations, and reassess with usage evidence.", indicators: { Cost: -1, Complexity: -1, Reliability: -1, "Time-to-market": 1 } },
    { id: "graceful", label: "Resilient application design with graceful degradation", consequence: "Maintains selected capabilities through some failures, with moderate added design effort.", rationale: "Prioritizes useful partial service when dependencies fail.", tradeoff: "Accepts additional engineering and operational complexity.", risk: "Degraded behavior may confuse users or return stale information.", mitigation: "Make capability status and freshness clear.", indicators: { Cost: 1, Complexity: 1, Reliability: 1 } },
    { id: "maximum", label: "Maximum redundancy for every dependency", consequence: "May improve resilience but can impose high cost and complexity regardless of capability criticality.", rationale: "Prioritizes broad redundancy where the business impact justifies it.", tradeoff: "Accepts substantial cost and operating complexity.", risk: "Investment may exceed the value of the protected capability.", mitigation: "Validate service levels and apply redundancy selectively.", indicators: { Cost: 1, Complexity: 1, Reliability: 1, "Time-to-market": -1 } },
  ]},
  { id: "action-capability", title: "Action capability", context: "Phase 2 may allow employees to create service requests through the assistant.", dimensions: ["Time-to-market", "Risk", "Authorization", "Auditability"], options: [
    { id: "transactions-now", label: "Enable controlled transactions in the first release", consequence: "Delivers action capability sooner but expands authorization, validation, integration, audit, and failure-handling scope.", rationale: "Prioritizes immediate business capability where controls can be delivered safely.", tradeoff: "Accepts greater initial risk and delivery complexity.", risk: "Incorrect or unauthorized service requests.", mitigation: "Use deterministic validation, scoped authorization, audit, and clear failure handling.", indicators: { Complexity: 1, Security: -1, "Time-to-market": -1 } },
    { id: "read-first", label: "Launch read-only first and introduce controlled transactions later", consequence: "Reduces first-release scope and risk while deferring action value.", rationale: "Sequences capability so transaction controls can be designed deliberately.", tradeoff: "Accepts delayed automation benefits.", risk: "Users may expect actions the first release cannot perform.", mitigation: "Communicate scope and provide clear handoff to existing service channels.", indicators: { Security: 1, Reliability: 1, "Time-to-market": 1 } },
    { id: "reject-actions", label: "Keep the assistant permanently read-only", consequence: "Avoids transaction risk but may unnecessarily constrain future business value.", rationale: "Fits workloads where action risk consistently outweighs benefit.", tradeoff: "Accepts limited capability and continued process friction.", risk: "The architecture cannot support valuable future automation.", mitigation: "Revisit the position if requirements, controls, or risk tolerance change.", indicators: { Complexity: -1, Security: 1, "Time-to-market": 1 } },
  ]},
];

const knowledgeQuestions = [
  { id: "requirement", prompt: "A sponsor says, ‘The requirement is to use a vector database.’ What is the strongest response?", answer: "reframe", options: [{ id: "accept", label: "Accept it as a fixed requirement" }, { id: "reframe", label: "Clarify the underlying grounding, freshness, and access need" }, { id: "replace", label: "Replace it with the largest model" }] },
  { id: "constraint", prompt: "A policy forbids confidential ticket data from leaving an approved boundary. How should this be treated?", answer: "constraint", options: [{ id: "feature", label: "As an optional feature" }, { id: "constraint", label: "As an architecture constraint that may eliminate designs" }, { id: "later", label: "As a post-launch concern" }] },
  { id: "tradeoff", prompt: "Live ITSM access improves freshness but adds runtime dependency. What is the architect’s task?", answer: "evaluate", options: [{ id: "always-live", label: "Always choose live access" }, { id: "always-cache", label: "Always choose caching" }, { id: "evaluate", label: "Evaluate freshness, availability, latency, and business impact together" }] },
  { id: "nfr", prompt: "The assistant answers correctly but becomes slow and expensive as usage grows. What was under-addressed?", answer: "qualities", options: [{ id: "prompt", label: "Prompt wording only" }, { id: "qualities", label: "Performance, scalability, operations, and cost requirements" }, { id: "branding", label: "Interface branding" }] },
  { id: "defensible", prompt: "Which architecture decision is most defensible?", answer: "traceable", options: [{ id: "popular", label: "The most popular technology choice" }, { id: "complex", label: "The design with the most components" }, { id: "traceable", label: "A decision linked to requirements, trade-offs, risks, and possible mitigations" }] },
];

function Header({ experience }: { experience: ArchitectThinkingExperienceDefinition }) { return <header className="experience-heading"><p className="eyebrow">{experience.eyebrow}</p><h1 tabIndex={-1}>{experience.title}</h1><p>{experience.summary}</p></header>; }
function Options({ name, options, selected, onSelect }: { name: string; options: Choice[]; selected?: string; onSelect: (id: string) => void }) { return <div className="architect-choice-list">{options.map((option) => <label className={selected === option.id ? "is-selected" : ""} key={option.id}><input type="radio" name={name} checked={selected === option.id} onChange={() => onSelect(option.id)} /><span><strong>{option.label}</strong>{selected === option.id && <small role="status">{option.consequence}</small>}</span></label>)}</div>; }

function Theory({ experience, state, onChange }: Props) {
  const complete = classificationItems.every((item) => state.classifications[item.id]);
  return <article className="experience-surface production-experience architect-thinking"><Header experience={experience} /><section className="habit-list" aria-label="Five architecture thinking habits">{habits.map((habit, index) => <details key={habit.title} open={index === 0}><summary><span>{String(index + 1).padStart(2, "0")}</span>{habit.title}</summary><p>{habit.body}</p>{habit.questions && <ul>{habit.questions.map((question) => <li key={question}>{question}</li>)}</ul>}{index === 0 && <div className="thinking-contrast"><p><small>Technology-first</small>“Which LLM should we use?”</p><p><small>Architecture-first</small>“What outcome are we trying to achieve, for whom, and under what conditions?”</p></div>}{index === 1 && <p className="architect-inline-insight">Preserve the requirement before committing to the implementation.</p>}{index === 3 && <p className="architect-inline-insight">The goal is not to maximize every quality. It is to make trade-offs consciously and defensibly.</p>}</details>)}</section><section className="classification-activity" aria-labelledby="classification-title"><p className="eyebrow">Try it</p><h2 id="classification-title">Requirement or proposed solution?</h2>{classificationItems.map((item) => { const selected = state.classifications[item.id]; return <fieldset key={item.id}><legend>{item.text}</legend><div><button className={selected === "requirement" ? "is-selected" : ""} type="button" aria-pressed={selected === "requirement"} onClick={() => onChange({ ...state, classifications: { ...state.classifications, [item.id]: "requirement" } })}>Requirement</button><button className={selected === "solution" ? "is-selected" : ""} type="button" aria-pressed={selected === "solution"} onClick={() => onChange({ ...state, classifications: { ...state.classifications, [item.id]: "solution" } })}>Proposed solution</button></div>{selected && <p role="status" className={selected === item.answer ? "is-aligned" : ""}>{selected === item.answer ? "Aligned." : "Reconsider."} {item.answer === "requirement" ? "This describes the outcome or condition the workload must satisfy." : "This commits to an implementation choice that should remain open until requirements and constraints are understood."}</p>}</fieldset>})}</section><aside className="architect-closing"><p>Architects do not only ask: <strong>Will this work?</strong></p><p>They also ask: Under what conditions will it work? What could change? What could fail? What trade-offs are we accepting?</p></aside><button className="primary-button" disabled={!complete} type="button" onClick={() => onChange({ ...state, completed: true })}>Apply the Thinking</button></article>;
}

function Scenario({ experience, state, onChange }: Props) {
  const step = Math.min(state.currentStep, scenarioReveals.length - 1); const reveal = scenarioReveals[step]; const selected = state.scenarioSelections[reveal.id]; const position = scenarioReveals.filter((item) => state.scenarioSelections[item.id]);
  if (state.completed) return <article className="experience-surface production-experience architect-thinking"><Header experience={experience} /><section className="architecture-position"><p className="eyebrow">Your architecture position</p><h2>AI Service Desk Assistant</h2>{position.map((item) => { const choice = item.options.find((option) => option.id === state.scenarioSelections[item.id]); return <article key={item.id}><strong>{item.label}</strong><p>{choice?.label}</p></article>})}<blockquote>Requirements rarely arrive all at once. Architects continually reassess decisions as new information appears.</blockquote></section></article>;
  return <article className="experience-surface production-experience architect-thinking"><Header experience={experience} /><section className="service-desk-brief"><p className="eyebrow">Continuous enterprise scenario</p><h2>AI Service Desk Assistant</h2><dl><div><dt>Organization</dt><dd>Large enterprise</dd></div><div><dt>Users</dt><dd>Approximately 20,000 employees</dd></div></dl><p>Employees need an AI-enabled service that can answer approved IT policy questions, explain common procedures, and check current service-ticket status.</p></section><div className="scenario-progress" aria-label={`Requirement ${step + 1} of ${scenarioReveals.length}`}>Requirement {step + 1} of {scenarioReveals.length}</div><section className="requirement-reveal" aria-live="polite"><p className="eyebrow">{reveal.label}</p><blockquote>{reveal.requirement}</blockquote><h2>{reveal.prompt}</h2><Options name={reveal.id} options={reveal.options} selected={selected} onSelect={(id) => onChange({ ...state, scenarioSelections: { ...state.scenarioSelections, [reveal.id]: id } })} /><div className="knowledge-controls"><button className="secondary-button" type="button" disabled={step === 0} onClick={() => onChange({ ...state, currentStep: step - 1 })}>Previous Requirement</button><button className="primary-button" type="button" disabled={!selected} onClick={() => step === scenarioReveals.length - 1 ? onChange({ ...state, completed: true }) : onChange({ ...state, currentStep: step + 1 })}>{step === scenarioReveals.length - 1 ? "View Architecture Position" : "Reveal Next Requirement"}</button></div></section></article>;
}

function TradeoffLab({ experience, state, onChange }: Props) {
  const step = Math.min(state.currentStep, tradeoffDecisions.length - 1); const decision = tradeoffDecisions[step]; const selected = state.tradeoffSelections[decision.id]; const allSelected = tradeoffDecisions.every((item) => state.tradeoffSelections[item.id]); const indicatorNames: Indicator[] = ["Cost", "Complexity", "Security", "Reliability", "Performance", "Time-to-market"];
  const scores = Object.values(state.tradeoffSelections).reduce<Record<Indicator, number>>((totals, optionId) => { const option = tradeoffDecisions.flatMap((item) => item.options).find((item) => item.id === optionId); indicatorNames.forEach((name) => totals[name] += option?.indicators?.[name] ?? 0); return totals; }, { Cost: 0, Complexity: 0, Security: 0, Reliability: 0, Performance: 0, "Time-to-market": 0 });
  const label = (score: number) => score > 1 ? "Increased pressure" : score < -1 ? "Reduced pressure" : "Balanced";
  if (state.completed) return <article className="experience-surface production-experience architect-thinking"><Header experience={experience} /><section className="adr" aria-labelledby="adr-title"><p className="eyebrow">Your Architecture Decision Record</p><h2 id="adr-title">AI Service Desk Assistant</h2>{tradeoffDecisions.map((item, index) => { const option = item.options.find((candidate) => candidate.id === state.tradeoffSelections[item.id])!; return <article key={item.id}><span>ADR {String(index + 1).padStart(2, "0")}</span><h3>{item.title}: {option.label}</h3><dl><div><dt>Why you chose it</dt><dd>{option.rationale}</dd></div><div><dt>Trade-off accepted</dt><dd>{option.tradeoff}</dd></div><div><dt>Risk / concern</dt><dd>{option.risk}</dd></div><div><dt>Possible mitigation</dt><dd>{option.mitigation}</dd></div></dl></article>})}</section><aside className="architect-closing"><strong>A defensible architecture decision connects:</strong><p>Requirement → Decision → Trade-off → Risk → Mitigation</p><p>Architecture is not only what you choose. It is also understanding what you accept by making that choice.</p></aside></article>;
  return <article className="experience-surface production-experience architect-thinking"><Header experience={experience} /><section className="lab-priorities"><p><strong>Business</strong>Launch quickly.</p><p><strong>Users</strong>Fast and useful responses.</p><p><strong>Security</strong>Protect confidential information.</p><p><strong>Operations</strong>Provide dependable service.</p><p><strong>Finance</strong>Control operating cost.</p><p><strong>Architect</strong>Balance the complete workload.</p></section><p>You cannot maximize every architecture quality independently. Your task is to make five defensible decisions.</p><div className="tradeoff-layout"><section className="tradeoff-decision" aria-live="polite"><p className="eyebrow">Decision {step + 1} of 5</p><h2>{decision.title}</h2><p>{decision.context}</p><p className="decision-dimensions">Dimensions: {decision.dimensions.join(" · ")}</p><Options name={decision.id} options={decision.options} selected={selected} onSelect={(id) => onChange({ ...state, tradeoffSelections: { ...state.tradeoffSelections, [decision.id]: id } })} /><div className="knowledge-controls"><button className="secondary-button" type="button" disabled={step === 0} onClick={() => onChange({ ...state, currentStep: step - 1 })}>Previous Decision</button><button className="primary-button" type="button" disabled={!selected} onClick={() => step < 4 && onChange({ ...state, currentStep: step + 1 })}>Next Decision</button></div></section><aside className="tradeoff-indicators"><p className="eyebrow">Directional indicators</p>{indicatorNames.map((name) => <div key={name}><span>{name}</span><strong>{label(scores[name])}</strong></div>)}<small>These indicators are directional learning aids, not quantitative architecture estimates.</small></aside></div>{allSelected && <section className="lab-reflection"><label htmlFor="tradeoff-reflection"><strong>Which trade-off was hardest to make, and why?</strong><small>Your response remains in this lesson session only.</small></label><textarea id="tradeoff-reflection" rows={4} value={state.reflectionResponse} onChange={(event) => onChange({ ...state, reflectionResponse: event.target.value })} /><button className="primary-button" type="button" disabled={!state.reflectionResponse.trim()} onClick={() => onChange({ ...state, completed: true })}>Generate Decision Record</button></section>}</article>;
}

function KnowledgeCheck({ experience, state, onChange }: Props) {
  const step = Math.min(state.currentStep, knowledgeQuestions.length - 1); const question = knowledgeQuestions[step]; const response = state.knowledgeResponses[question.id] ?? { selectedOptionId: null, submitted: false, attempts: 0 };
  if (state.completed) return <article className="experience-surface production-experience architect-thinking"><Header experience={experience} /><section className="architect-lesson-complete" role="status"><p className="eyebrow">How Enterprise AI Architects Think — Complete</p><h2>You practiced five architecture habits</h2><ul>{["Start with outcomes", "Separate requirements from solutions", "Identify constraints", "Reason in trade-offs", "Design for change"].map((item) => <li key={item}><ArchitectingAiIcon name="complete" size={17} />{item}</li>)}</ul><p>You also created an Architecture Decision Record by connecting requirements, decisions, trade-offs, risks, and mitigations.</p><blockquote>The best architecture is not the one with the most technology. It is the one whose decisions can be explained and defended against the workload&apos;s requirements and constraints.</blockquote><aside><span>Next</span><strong><ArchitectingAiIcon name="assessment" size={18} />Enterprise AI Architecture Assessment</strong><p>10 scenario-based questions · Percentage score · Review and retry where appropriate · Certificate after satisfying the defined criteria</p><button className="secondary-button" type="button" disabled>Coming next</button></aside></section></article>;
  const update = (patch: Partial<typeof response>) => onChange({ ...state, knowledgeResponses: { ...state.knowledgeResponses, [question.id]: { ...response, ...patch } } });
  return <article className="experience-surface production-experience architect-thinking"><Header experience={experience} /><section className="knowledge-progress"><span>Question {step + 1} of 5</span><div>{knowledgeQuestions.map((item, index) => <i className={index <= step ? "is-reached" : ""} key={item.id} />)}</div></section><section className="knowledge-question"><fieldset disabled={response.submitted}><legend>{question.prompt}</legend>{question.options.map((option) => <label className={response.selectedOptionId === option.id ? "is-selected" : ""} key={option.id}><input type="radio" name={question.id} checked={response.selectedOptionId === option.id} onChange={() => update({ selectedOptionId: option.id, submitted: false })} /><span>{option.label}</span></label>)}</fieldset>{!response.submitted ? <button className="primary-button" type="button" disabled={!response.selectedOptionId} onClick={() => update({ submitted: true, attempts: response.attempts + 1 })}>Review Decision</button> : <div className="knowledge-feedback" role="status"><strong>{response.selectedOptionId === question.answer ? "Defensible reasoning" : "Reconsider this position"}</strong><p>{response.selectedOptionId === question.answer ? "Your choice connects the scenario to the relevant architecture principle." : "Look for the option that keeps the decision traceable to requirements, constraints, and consequences."}</p></div>}<div className="knowledge-controls"><button className="secondary-button" type="button" disabled={step === 0} onClick={() => onChange({ ...state, currentStep: step - 1 })}>Previous Question</button><button className="primary-button" type="button" disabled={!response.submitted} onClick={() => step === 4 ? onChange({ ...state, completed: true }) : onChange({ ...state, currentStep: step + 1 })}>{step === 4 ? "Complete Lesson" : "Next Question"}</button></div></section></article>;
}

interface Props { experience: ArchitectThinkingExperienceDefinition; state: ArchitectThinkingState; onChange: (state: ArchitectThinkingState) => void; }
export function ArchitectThinkingExperience(props: Props) {
  if (props.experience.kind === "theory") return <Theory {...props} />;
  if (props.experience.kind === "scenario") return <Scenario {...props} />;
  if (props.experience.kind === "tradeoff-lab") return <TradeoffLab {...props} />;
  return <KnowledgeCheck {...props} />;
}
