"use client";

import { useState } from "react";
import { EnterpriseArchitectureExplorer } from "@/modules/architecture-explorer/components/enterprise-architecture-explorer";
import { enterpriseAiArchitecture } from "@/modules/architecture-explorer/enterprise-ai-example";
import type { ArchitectureLearningModelExperienceDefinition, EnterpriseRequestFlowExperienceDefinition, RequirementsRealityCheckExperienceDefinition } from "../types";

function ProductionHeader({ experience }: { experience: { eyebrow?: string; title: string; summary?: string } }) {
  return <header className="experience-heading"><p className="eyebrow">{experience.eyebrow}</p><h1 tabIndex={-1}>{experience.title}</h1>{experience.summary && <p>{experience.summary}</p>}</header>;
}

export function ArchitectureLearningModelExperience({ experience }: { experience: ArchitectureLearningModelExperienceDefinition }) {
  const [selectedDomainId, setSelectedDomainId] = useState<string | null>(null); const [stepIndex, setStepIndex] = useState(0); const step = experience.guidedSteps[stepIndex]; const isFinal = stepIndex === experience.guidedSteps.length - 1; const previousIds = new Set(stepIndex ? experience.guidedSteps[stepIndex - 1].nodeIds : []);
  const visibleNodes = enterpriseAiArchitecture.nodes.filter((node) => step.nodeIds.includes(node.id));
  return <article className="experience-surface production-experience block-two-experience"><ProductionHeader experience={experience} /><blockquote className="core-statement">“{experience.statement}”</blockquote><aside className="model-qualification"><strong>Architecting AI — Enterprise AI Architecture Learning Model</strong><p>{experience.qualification}</p></aside><section className={`guided-architecture ${isFinal ? "is-complete" : ""}`} aria-labelledby={`${experience.id}-step-title`}><div className="guided-step-copy" aria-live="polite"><p className="eyebrow">Step {stepIndex + 1} of {experience.guidedSteps.length}</p><h2 id={`${experience.id}-step-title`}>{step.title}</h2><p>{step.cue}</p></div>{!isFinal ? <figure className="guided-model"><figcaption>Architecture domains introduced so far</figcaption><div className="guided-model-grid">{visibleNodes.map((node) => <div className={`guided-model-node ${previousIds.has(node.id) ? "is-revealed" : "is-active"} ${node.crossCutting ? "is-cross-cutting" : ""}`} key={node.id}><strong>{node.label}</strong><small>{enterpriseAiArchitecture.domains.find((domain) => domain.id === node.domainId)?.label}</small></div>)}</div><p className="sr-only">Visible architecture elements: {visibleNodes.map((node) => node.label).join(", ")}.</p></figure> : <><p className="explorer-instruction"><strong>Select any architecture domain</strong> to explore its role and relationships.</p><div className="block-two-explorer"><EnterpriseArchitectureExplorer selectedDomainId={selectedDomainId} onSelectedDomainChange={setSelectedDomainId} /></div><p className="relationship-reminder">The model shows connected concerns—not a required request sequence.</p></>}<div className="story-controls"><button className="secondary-button" type="button" disabled={stepIndex === 0} onClick={() => setStepIndex((index) => index - 1)}>Previous</button><button className="secondary-button" type="button" onClick={() => { setStepIndex(0); setSelectedDomainId(null); }}>Replay</button><button className="primary-button" type="button" disabled={isFinal} onClick={() => setStepIndex((index) => index + 1)}>Next</button></div></section></article>;
}

export function EnterpriseRequestFlowExperience({ experience }: { experience: EnterpriseRequestFlowExperienceDefinition }) {
  const [stepIndex, setStepIndex] = useState(0); const [answer, setAnswer] = useState<string | null>(null); const [submitted, setSubmitted] = useState(false); const step = experience.steps[stepIndex];
  const selectStep = (index: number) => setStepIndex(index);
  return <article className="experience-surface production-experience block-two-experience"><ProductionHeader experience={experience} /><blockquote className="request-scenario">Employee asks: “{experience.scenario}”</blockquote><section className="request-flow" aria-label="Guided enterprise request journey"><nav className="request-journey" aria-label="Request flow steps">{experience.steps.map((item,index) => <button type="button" className={index === stepIndex ? "is-current" : index < stepIndex ? "is-reached" : ""} aria-current={index === stepIndex ? "step" : undefined} onClick={() => selectStep(index)} key={item.id}><span>{index < stepIndex ? "✓" : String(index + 1).padStart(2,"0")}</span><strong>{item.domain}</strong></button>)}</nav><div className="request-active-wrap"><div className="request-flow-copy" aria-live="polite"><div className="active-step-icon" aria-hidden="true">{String(stepIndex + 1).padStart(2,"0")}</div><p className="eyebrow">Step {stepIndex + 1} of {experience.steps.length} · {step.domain}</p><h2>{step.title}</h2><p>{step.explanation}</p>{step.telemetry && <div className="telemetry-row" aria-label="Example operational telemetry">{step.telemetry.map((item) => <span key={item}>{item}</span>)}</div>}</div><div className="story-controls"><button className="secondary-button" type="button" disabled={stepIndex === 0} onClick={() => selectStep(stepIndex - 1)}>Previous Step</button><button className="secondary-button" type="button" onClick={() => selectStep(0)}>Replay</button><button className="primary-button" type="button" disabled={stepIndex === experience.steps.length - 1} onClick={() => selectStep(stepIndex + 1)}>Next Step</button></div></div><ol className="sr-only">{experience.steps.map((item) => <li key={item.id}>{item.title}: {item.explanation}</li>)}</ol></section><form className="flow-knowledge" onSubmit={(event) => { event.preventDefault(); if (answer) setSubmitted(true); }}><fieldset><legend>{experience.question.prompt}</legend>{experience.question.options.map((option) => <label className={answer === option.id ? "is-selected" : ""} key={option.id}><input type="radio" name={experience.question.id} value={option.id} checked={answer === option.id} onChange={() => { setAnswer(option.id); setSubmitted(false); }} /><span>{option.label}</span></label>)}</fieldset><button className="primary-button" type="submit" disabled={!answer}>Check understanding</button>{submitted && <div className="educational-feedback" role="status"><strong>{answer === experience.question.answerOptionId ? "That’s the strongest answer." : "Reconsider the source of the current business fact."}</strong><p>{answer === experience.question.answerOptionId ? experience.question.feedback : experience.question.retryPrompt}</p></div>}</form></article>;
}

export function RequirementsRealityCheckExperience({ experience }: { experience: RequirementsRealityCheckExperienceDefinition }) {
  const [selectedId, setSelectedId] = useState(experience.changes[0].id); const selected = experience.changes.find((item) => item.id === selectedId) ?? experience.changes[0];
  return <article className="experience-surface production-experience block-two-experience reality-check-experience"><ProductionHeader experience={experience} /><section className="reality-baseline"><p className="eyebrow">Baseline · HR Policy Assistant</p><ul>{experience.baseline.map((item) => <li key={item}>{item}</li>)}</ul></section><h2 className="reality-prompt">{experience.prompt}</h2><div className="reality-layout"><div className="reality-change-list" role="list" aria-label="Requirement changes">{experience.changes.map((change,index) => <button type="button" className={change.id === selectedId ? "is-selected" : ""} aria-pressed={change.id === selectedId} onClick={() => setSelectedId(change.id)} key={change.id}><span>Change {index + 1}</span><strong>{change.from}</strong><i aria-hidden="true">→</i><strong>{change.to}</strong></button>)}</div><section className="reality-impact" aria-live="polite"><p className="eyebrow">Architecture impact</p><h3>{selected.prompt}</h3><ul>{selected.considerations.map((item) => <li key={item}>{item}</li>)}</ul><blockquote>{selected.teachingPoint}</blockquote></section></div><aside className="production-insight"><p className="eyebrow">Architect Insight</p><strong>{experience.finalPrinciple}</strong></aside></article>;
}
