"use client";

import { useState } from "react";
import { EnterpriseArchitectureExplorer } from "@/modules/architecture-explorer/components/enterprise-architecture-explorer";
import type { ArchitectInsightExperienceDefinition, ConceptExperienceDefinition, DiagramExperienceDefinition, EnterpriseExampleExperienceDefinition, IntroductionExperienceDefinition, SummaryExperienceDefinition } from "../types";

export function IntroductionExperience({ experience }: { experience: IntroductionExperienceDefinition }) { return <ExperienceSurface experience={experience}><ul className="objective-list">{experience.objectives.map((objective) => <li key={objective.id}>{objective.statement}</li>)}</ul></ExperienceSurface>; }
export function ConceptExperience({ experience }: { experience: ConceptExperienceDefinition }) { return <ExperienceSurface experience={experience}>{experience.points && <div className="concept-points">{experience.points.map((point, index) => <div key={point}><span>0{index + 1}</span><p>{point}</p></div>)}</div>}</ExperienceSurface>; }
export function EnterpriseExampleExperience({ experience }: { experience: EnterpriseExampleExperienceDefinition }) { return <ExperienceSurface experience={experience}><div className="enterprise-example"><p className="example-org">{experience.example.organization}</p><h2>{experience.example.situation}</h2><p>{experience.example.response}</p></div></ExperienceSurface>; }
export function ArchitectInsightExperience({ experience }: { experience: ArchitectInsightExperienceDefinition }) { return <ExperienceSurface experience={experience}><blockquote className="architect-quote">{experience.insight.statement}</blockquote><p className="experience-detail">{experience.insight.explanation}</p></ExperienceSurface>; }
export function SummaryExperience({ experience, complete }: { experience: SummaryExperienceDefinition; complete: boolean }) { return <ExperienceSurface experience={experience}><ul className="summary-outcomes">{experience.outcomes.map((outcome) => <li key={outcome}>{outcome}</li>)}</ul>{complete && <p className="demo-complete" role="status">Demo learning experience complete.</p>}</ExperienceSurface>; }
export function DiagramExperience({ experience }: { experience: DiagramExperienceDefinition }) { const [selectedDomainId, setSelectedDomainId] = useState<string | null>(null); return <ExperienceSurface experience={experience}><div className="lesson-diagram"><p className="demo-data-label">Diagram source: {experience.diagramId ?? experience.architectureScenarioId}</p><EnterpriseArchitectureExplorer selectedDomainId={selectedDomainId} onSelectedDomainChange={setSelectedDomainId} /></div></ExperienceSurface>; }

function ExperienceSurface({ experience, children }: { experience: { eyebrow?: string; title: string; summary?: string }; children?: React.ReactNode }) { return <article className="experience-surface"><header className="experience-heading">{experience.eyebrow && <p className="eyebrow">{experience.eyebrow}</p>}<h1 tabIndex={-1}>{experience.title}</h1>{experience.summary && <p>{experience.summary}</p>}</header>{children}</article>; }
