import type { KnowledgeCheckExperienceDefinition, KnowledgeCheckResponse } from "../types";

export function KnowledgeCheckExperience({ experience, response, onChange }: { experience: KnowledgeCheckExperienceDefinition; response?: KnowledgeCheckResponse; onChange: (response: KnowledgeCheckResponse) => void }) {
  const selectedId = response?.selectedOptionId ?? null; const submitted = response?.submitted ?? false; const isBestResponse = selectedId === experience.question.answerOptionId;
  const select = (selectedOptionId: string) => onChange({ selectedOptionId, submitted: false, attempts: response?.attempts ?? 0 });
  const submit = () => selectedId && onChange({ selectedOptionId: selectedId, submitted: true, attempts: (response?.attempts ?? 0) + 1 });
  const retry = () => onChange({ selectedOptionId: null, submitted: false, attempts: response?.attempts ?? 1 });
  return <article className="experience-surface"><header className="experience-heading"><p className="eyebrow">{experience.eyebrow}</p><h1 tabIndex={-1}>{experience.title}</h1><p>{experience.question.prompt}</p></header><fieldset className="lesson-choice-list"><legend>Select one response</legend>{experience.question.options.map((option, index) => <label key={option.id} className={`lesson-choice ${selectedId === option.id ? "is-selected" : ""}`}><input type="radio" name={experience.question.id} checked={selectedId === option.id} disabled={submitted} onChange={() => select(option.id)} /><span className="option-letter">{String.fromCharCode(65 + index)}</span><span>{option.label}</span>{selectedId === option.id && <strong>Selected</strong>}</label>)}</fieldset>{!submitted && <button className="primary-button check-submit" type="button" disabled={!selectedId} onClick={submit}>Review Response</button>}{submitted && <div className="knowledge-feedback" role="status"><p className="feedback-label">Architectural feedback</p><p>{isBestResponse ? experience.question.feedback : experience.question.retryPrompt}</p>{!isBestResponse && <button className="secondary-button" type="button" onClick={retry}>Try Again</button>}</div>}</article>;
}
