"use client";

import Link from "next/link";
import { ArchitectingAiIcon } from "@/components/icons";
import type { LessonSummaryReflectionExperienceDefinition, LessonSummaryReflectionState, ScenarioKnowledgeCheckExperienceDefinition, ScenarioKnowledgeCheckState } from "../types";

function Header({ experience }: { experience: { eyebrow?: string; title: string; summary?: string } }) { return <header className="experience-heading"><p className="eyebrow">{experience.eyebrow}</p><h1 tabIndex={-1}>{experience.title}</h1>{experience.summary && <p>{experience.summary}</p>}</header>; }

export function ScenarioKnowledgeCheckExperience({ experience, state, onChange }: { experience: ScenarioKnowledgeCheckExperienceDefinition; state: ScenarioKnowledgeCheckState; onChange: (state: ScenarioKnowledgeCheckState) => void }) {
  const question = experience.questions[state.currentQuestionIndex];
  const response = state.responses[question.id] ?? { selectedOptionId: null, submitted: false, attempts: 0 };
  const alignedCount = experience.questions.filter((item) => state.responses[item.id]?.selectedOptionId === item.preferredOptionId).length;
  const select = (selectedOptionId: string) => onChange({ ...state, responses: { ...state.responses, [question.id]: { ...response, selectedOptionId, submitted: false } } });
  const submit = () => { if (!response.selectedOptionId) return; onChange({ ...state, responses: { ...state.responses, [question.id]: { ...response, submitted: true, attempts: response.attempts + 1 } } }); };
  const next = () => state.currentQuestionIndex === experience.questions.length - 1 ? onChange({ ...state, completed: true }) : onChange({ ...state, currentQuestionIndex: state.currentQuestionIndex + 1 });

  if (state.completed) return <article className="experience-surface production-experience scenario-knowledge-check"><Header experience={experience} /><section className="knowledge-result" role="status"><p className="eyebrow">Reasoning summary</p><h2>{alignedCount} of {experience.questions.length} architecture decisions aligned with the lesson principles.</h2><p>{alignedCount >= 4 ? "You are applying the core architecture principles consistently." : "Review the reasoning behind the decisions you found challenging before continuing."}</p><ul>{experience.questions.map((item, index) => <li key={item.id}><span>Decision {index + 1}</span><strong>{state.responses[item.id]?.selectedOptionId === item.preferredOptionId ? "Preferred reasoning" : "Reasoning to revisit"}</strong></li>)}</ul></section></article>;

  return <article className="experience-surface production-experience scenario-knowledge-check"><Header experience={experience} /><section className="knowledge-progress" aria-label={`Question ${state.currentQuestionIndex + 1} of ${experience.questions.length}`}><span>Question {state.currentQuestionIndex + 1} of {experience.questions.length}</span><div>{experience.questions.map((item, index) => <i className={index <= state.currentQuestionIndex ? "is-reached" : ""} key={item.id} />)}</div></section><section className="knowledge-question" aria-labelledby={`${question.id}-prompt`}><p className="eyebrow">Scenario</p><blockquote>{question.scenario}</blockquote><fieldset disabled={response.submitted}><legend id={`${question.id}-prompt`}>{question.prompt}</legend>{question.options.map((option) => <label className={response.selectedOptionId === option.id ? "is-selected" : ""} key={option.id}><input type="radio" name={question.id} checked={response.selectedOptionId === option.id} onChange={() => select(option.id)} /><span>{option.label}</span></label>)}</fieldset>{!response.submitted ? <button className="primary-button" type="button" disabled={!response.selectedOptionId} onClick={submit}>Review Decision</button> : <div className="knowledge-feedback" role="status" aria-live="polite"><strong>{response.selectedOptionId === question.preferredOptionId ? "Preferred reasoning" : "Reconsider this decision"}</strong>{question.feedback.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div>}<div className="knowledge-controls"><button className="secondary-button" type="button" disabled={state.currentQuestionIndex === 0} onClick={() => onChange({ ...state, currentQuestionIndex: state.currentQuestionIndex - 1 })}>Previous Question</button><button className="primary-button" type="button" disabled={!response.submitted} onClick={next}>{state.currentQuestionIndex === experience.questions.length - 1 ? "View Result" : "Next Question"}</button></div></section></article>;
}

export function LessonSummaryReflectionExperience({ experience, state, onChange }: { experience: LessonSummaryReflectionExperienceDefinition; state: LessonSummaryReflectionState; onChange: (state: LessonSummaryReflectionState) => void }) {
  return <article className="experience-surface production-experience lesson-summary-reflection">
    <Header experience={{ ...experience, title: "What You Have Learned" }} />
    <p className="summary-introduction">{experience.introduction}</p>
    <section className="part-one-journey" aria-labelledby="journey-title"><p className="eyebrow">The learning journey</p><h2 id="journey-title">Why, understand, apply</h2><div>{experience.lessons.map((lesson, index) => <article key={lesson.id}><span className="journey-theme">{lesson.theme}</span><small>{lesson.lessonLabel}</small><h3>{lesson.title}</h3>{lesson.summary.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<ul>{lesson.keyIdeas.map((idea) => <li key={idea}>{idea}</li>)}</ul>{index < experience.lessons.length - 1 && <span className="journey-arrow" aria-hidden="true">→</span>}</article>)}</div></section>
    <section className="architect-mental-model" aria-labelledby="mental-model-title"><p className="eyebrow">Architect&apos;s mental model</p><h2 id="mental-model-title">Reframe the starting question</h2><div className="mental-model-shift"><div><small>From</small><blockquote>{experience.mentalModel.from}</blockquote></div><span aria-hidden="true">→</span><div><small>To</small><blockquote>{experience.mentalModel.to}</blockquote></div></div><ol>{experience.mentalModel.sequence.map((item) => <li key={item}>{item}</li>)}</ol><p>{experience.mentalModel.qualification}</p></section>
    <section className="part-one-capabilities" aria-labelledby="capabilities-title"><p className="eyebrow">What you can now do</p><h2 id="capabilities-title">After completing Part 1, you can:</h2><ul>{experience.capabilities.map((capability) => <li key={capability}><ArchitectingAiIcon name="complete" size={17} />{capability}</li>)}</ul></section>
    <section className="summary-reflection"><label htmlFor={`${experience.id}-reflection`}><span className="eyebrow">Reflection</span><strong>{experience.reflectionPrompt}</strong><small>{experience.reflectionHelper}</small></label><textarea id={`${experience.id}-reflection`} rows={5} value={state.reflectionResponse} onChange={(event) => onChange({ ...state, reflectionResponse: event.target.value })} /></section>
    <aside className="summary-architect-takeaway"><p className="eyebrow">Architect Takeaway</p>{experience.architectTakeaway.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<p>AI is part of the architecture — not the architecture itself.</p></aside>
    {!state.completed && <button className="primary-button" type="button" disabled={!state.reflectionResponse.trim()} onClick={() => onChange({ ...state, completed: true })}>Complete Part 1</button>}
    {state.completed && <section className="part-one-complete" role="status"><ArchitectingAiIcon name="complete" size={28} /><div><p className="eyebrow">Part 1 Complete</p><h2>Enterprise AI Architecture Foundations</h2><p>{experience.completionStatement}</p></div></section>}
    <section className="part-one-next" aria-labelledby="coming-next-title"><p className="eyebrow">Continue learning</p><h2 id="coming-next-title">{experience.nextLessonTitle}</h2>{experience.nextLessonDescription && <p>{experience.nextLessonDescription}</p>}{experience.nextLessonHref ? <Link className="primary-button button-link" href={experience.nextLessonHref}>Continue Learning</Link> : <button className="secondary-button" type="button" disabled>Continue Learning · Coming Soon</button>}</section>
  </article>;
}
