"use client";

import type { ArchitectureComparisonExperienceDefinition, EnterpriseReadinessChallengeDefinition, ProgressiveArchitectureExperienceDefinition, ProgressiveArchitectureState } from "../types";

export function EnterpriseReadinessChallenge({ experience, selectedIds, submitted, onSelectionChange, onSubmit }: { experience: EnterpriseReadinessChallengeDefinition; selectedIds: string[]; submitted: boolean; onSelectionChange: (ids: string[]) => void; onSubmit: () => void }) {
  const toggle = (id: string) => onSelectionChange(selectedIds.includes(id) ? selectedIds.filter((item) => item !== id) : [...selectedIds, id]);
  return <article className="experience-surface production-experience"><header className="experience-heading"><p className="eyebrow">{experience.eyebrow}</p><h1 tabIndex={-1}>{experience.title}</h1><p>{experience.summary}</p></header><div className="opening-challenge"><section className="scenario-copy"><p>{experience.scenario[0]}</p><p>Employees can ask questions such as:</p><blockquote>“{experience.examples[0]}”</blockquote>{experience.scenario.slice(1).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</section><PrototypeVisual /><blockquote className="cio-question"><span>The CIO asks</span>“{experience.cioQuestion}”</blockquote></div><form className="readiness-form" onSubmit={(event) => { event.preventDefault(); onSubmit(); }}><fieldset disabled={submitted}><legend>{experience.prompt}</legend><p>{experience.instruction}</p><div className="readiness-options">{experience.options.map((option) => <label key={option.id} className={selectedIds.includes(option.id) ? "is-selected" : ""}><input type="checkbox" checked={selectedIds.includes(option.id)} onChange={() => toggle(option.id)} /><span>{option.label}</span></label>)}</div></fieldset>{!submitted && <button className="primary-button" type="submit" disabled={!selectedIds.length}>Reveal Architect Insight</button>}</form>{submitted && <section className="production-insight" role="status"><p className="eyebrow">Architect Insight</p>{experience.insight.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<p className="insight-support">{experience.workloadExplanation}</p></section>}</article>;
}

export function ArchitectureComparisonExperience({ experience }: { experience: ArchitectureComparisonExperienceDefinition }) {
  return <article className="experience-surface production-experience"><header className="experience-heading"><p className="eyebrow">{experience.eyebrow}</p><h1 tabIndex={-1}>{experience.title}</h1><p>{experience.summary}</p></header><p className="core-statement">{experience.coreStatement}</p>{experience.explanation.map((paragraph) => <p className="comparison-explanation" key={paragraph}>{paragraph}</p>)}<div className="prototype-comparison"><section><p className="eyebrow">Prototype question</p><FlowNodes nodes={experience.prototypeFlow} /><blockquote>“{experience.prototypeQuestion}”</blockquote></section><section><p className="eyebrow">Architecture questions</p><div className="architecture-question-list">{experience.architectureQuestions.map((item) => <details key={item.id}><summary>{item.question}</summary><p>{item.explanation}</p></details>)}</div></section></div><section className="production-insight"><p className="eyebrow">Architect Insight · Best Practice</p>{experience.insight.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<strong>{experience.emphasis}</strong></section></article>;
}

export function ProgressiveArchitectureExperience({ experience, state, onChange }: { experience: ProgressiveArchitectureExperienceDefinition; state: ProgressiveArchitectureState; onChange: (state: ProgressiveArchitectureState) => void }) {
  const scene = experience.scenes[state.sceneIndex]; const isFirst = state.sceneIndex === 0; const isLast = state.sceneIndex === experience.scenes.length - 1;
  return <article className="experience-surface production-experience"><header className="experience-heading"><p className="eyebrow">{experience.eyebrow}</p><h1 tabIndex={-1}>{experience.title}</h1><p>{experience.summary}</p></header><section className="architecture-story" aria-live="polite"><div className="story-progress"><span>Scene {state.sceneIndex + 1} of {experience.scenes.length}</span><div>{experience.scenes.map((item, index) => <i className={index <= state.sceneIndex ? "is-reached" : ""} key={item.id} />)}</div></div><div className="story-layout"><div className="story-copy"><p className="eyebrow">{scene.title}</p>{scene.prompt && <blockquote>“{scene.prompt}”</blockquote>}{scene.teachingCopy.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{scene.accuracyCallout && <aside><strong>Architecture accuracy</strong><p>{scene.accuracyCallout}</p></aside>}</div><ProgressiveArchitectureVisual experience={experience} sceneIndex={state.sceneIndex} /></div><div className="story-controls"><button className="secondary-button" type="button" disabled={isFirst} onClick={() => onChange({ ...state, sceneIndex: state.sceneIndex - 1 })}>Previous</button><button className="secondary-button" type="button" onClick={() => onChange({ ...state, sceneIndex: 0 })}>Replay</button><button className="primary-button" type="button" disabled={isLast} onClick={() => onChange({ ...state, sceneIndex: state.sceneIndex + 1 })}>Next</button></div></section>{isLast && <><blockquote className="block-insight">{experience.blockInsight}</blockquote><form className="quick-reflection" onSubmit={(event) => { event.preventDefault(); if (state.reflectionResponse.trim()) onChange({ ...state, reflectionSubmitted: true }); }}><label htmlFor={`${experience.id}-reflection`}><span className="eyebrow">Quick reflection</span><strong>{experience.reflectionPrompt}</strong></label><textarea id={`${experience.id}-reflection`} rows={4} value={state.reflectionResponse} disabled={state.reflectionSubmitted} onChange={(event) => onChange({ ...state, reflectionResponse: event.target.value })} />{!state.reflectionSubmitted ? <button className="primary-button" type="submit" disabled={!state.reflectionResponse.trim()}>Reveal Reflection</button> : <div className="reflection-reveal" role="status">{experience.reflectionReveal}</div>}</form></>}</article>;
}

function PrototypeVisual() { return <figure className="prototype-visual"><figcaption>Prototype</figcaption><FlowNodes nodes={["Employee", "AI Application", "Model"]} /><div className="unrevealed-concerns" aria-hidden="true"><span /><span /><span /><span /></div><p className="sr-only">Prototype flow from employee to AI application to model, surrounded by unresolved enterprise concerns.</p></figure>; }
function FlowNodes({ nodes }: { nodes: string[] }) { return <div className="flow-nodes">{nodes.map((node, index) => <span key={node}>{node}{index < nodes.length - 1 && <i aria-hidden="true">→</i>}</span>)}</div>; }

function ProgressiveArchitectureVisual({ experience, sceneIndex }: { experience: ProgressiveArchitectureExperienceDefinition; sceneIndex: number }) {
  const visible = experience.scenes.slice(0, sceneIndex + 1).flatMap((scene) => scene.introducedCapabilities); const final = sceneIndex === experience.scenes.length - 1;
  if (final) return <figure className="enterprise-learning-model"><figcaption>{experience.finalModel.title}</figcaption><div className="model-cross"><strong>Cross-cutting</strong>{experience.finalModel.crossCutting.map((item) => <span key={item}>{item}</span>)}</div><div className="model-layers">{experience.finalModel.layers.map((layer) => <div key={layer}><strong>{layer}</strong>{layer === "AI & Intelligence" && <small>{experience.finalModel.intelligenceOptions.join(" · ")}</small>}</div>)}</div><div className="model-foundation"><strong>Operational foundation</strong>{experience.finalModel.foundation.map((item) => <span key={item}>{item}</span>)}</div><p className="model-relationship-note">{experience.finalModel.relationshipNote}</p><p>{experience.finalModel.qualification}</p></figure>;
  return <figure className="progressive-model"><figcaption>Architecture capabilities introduced so far</figcaption><div className="progressive-core"><FlowNodes nodes={["Employee", "AI Application", "Model"]} /></div><div className="introduced-capabilities">{visible.filter((item) => !["Employee", "AI Application", "Model"].includes(item)).map((item) => <span key={item}>{item}</span>)}</div><p className="sr-only">Current architecture includes {visible.join(", ")}.</p></figure>;
}
