"use client";

import { reviewArchitectureLab } from "../review-architecture-lab";
import type { ArchitectureLabExperienceDefinition } from "@/modules/learning-experience/types";
import type { ArchitectureLabFeedback, ArchitectureLabPlacement, ArchitectureLabState } from "../types";
import { ArchitectureToolkit } from "./architecture-toolkit";
import { CapabilityMatchingActivity } from "./capability-matching-activity";

export function ArchitectureLabExperience({ experience, state, onChange }: { experience: ArchitectureLabExperienceDefinition; state: ArchitectureLabState; onChange: (state: ArchitectureLabState) => void }) {
  const { lab } = experience;
  const assign = (componentId: string) => { if (!state.activeSlotId) return; const placements = [...state.placements.filter((placement) => placement.slotId !== state.activeSlotId), { slotId: state.activeSlotId, componentId }]; onChange({ ...state, placements }); };
  const remove = (slotId: string) => onChange({ ...state, placements: state.placements.filter((placement) => placement.slotId !== slotId) });
  const minimumReady = state.placements.length >= lab.completionCriteria.minimumPlacements && lab.completionCriteria.requiredSlotIds.every((slotId) => state.placements.some((placement) => placement.slotId === slotId));
  const review = () => { const attemptNumber = state.attemptNumber + 1; const feedback = reviewArchitectureLab(lab, state.placements); const attempt = { attemptNumber, placements: state.placements.map((placement) => ({ ...placement })), feedback }; onChange({ ...state, attemptNumber, reviewHistory: [...state.reviewHistory, attempt], latestFeedback: feedback, phase: "review" }); };
  const challengeOption = lab.finalChallenge.options.find((option) => option.id === state.finalChallengeResponse);

  if (state.phase === "complete") return <article className="experience-surface architecture-lab"><header className="experience-heading"><p className="eyebrow">Architecture Lab complete</p><h1 tabIndex={-1}>You transformed a prototype into a more complete enterprise system.</h1><p>You considered identity, data, integration, security, governance and operations as connected architecture decisions.</p></header><ul className="lab-completion-list">{state.placements.map((placement) => <li key={placement.slotId}>{lab.availableComponents.find((component) => component.id === placement.componentId)?.label}</li>)}</ul><p className="lab-continue-hint">Continue Lesson →</p></article>;

  return <article className="experience-surface architecture-lab"><header className="experience-heading"><p className="eyebrow">{experience.eyebrow} · Demo content</p><h1 tabIndex={-1}>{experience.title}</h1><p>{experience.summary}</p></header>
    {state.phase === "matching" && <><section className="lab-brief" aria-labelledby="lab-scenario-title"><div><p className="eyebrow">Enterprise scenario</p><h2 id="lab-scenario-title">{lab.scenario.title}</h2><p>{lab.scenario.description}</p><small>{lab.scenario.context}</small></div><div><h3>New requirements</h3><ul>{lab.requirements.map((requirement) => <li key={requirement.id}>{requirement.statement}</li>)}</ul></div></section><CapabilityMatchingActivity definition={lab.capabilityMatching} responses={state.matchingResponses} activePromptId={state.activeMatchingPromptId} reviewed={state.matchingReviewed} onActivePromptChange={(activeMatchingPromptId) => onChange({ ...state, activeMatchingPromptId })} onResponsesChange={(matchingResponses) => onChange({ ...state, matchingResponses, activeMatchingPromptId: null })} onReview={() => onChange({ ...state, matchingReviewed: true, activeMatchingPromptId: null })} onContinue={() => onChange({ ...state, phase: "design" })} /></>}
    {state.phase === "design" && <><section className="lab-brief" aria-labelledby="lab-scenario-title"><div><p className="eyebrow">Enterprise scenario</p><h2 id="lab-scenario-title">{lab.scenario.title}</h2><p>{lab.scenario.description}</p><small>{lab.scenario.context}</small></div><div><h3>New requirements</h3><ul>{lab.requirements.map((requirement) => <li key={requirement.id}>{requirement.statement}</li>)}</ul></div></section><section className="starting-architecture" aria-label="Starting prototype architecture"><p>Starting prototype</p><ol>{lab.startingArchitecture.map((node) => <li key={node}>{node}</li>)}</ol></section><div className="lab-builder"><ArchitectureSlots lab={lab} state={state} onActivate={(activeSlotId) => onChange({ ...state, activeSlotId })} onRemove={remove} /><ArchitectureToolkit components={lab.availableComponents} placements={state.placements} activeSlotId={state.activeSlotId} onAssign={assign} /></div><div className="lab-review-bar"><div><strong>{state.attemptNumber ? `Refinement attempt ${state.attemptNumber + 1}` : "Design your architecture"}</strong><span>{state.placements.length} of {lab.slots.length} positions configured</span>{!minimumReady && <small>Configure at least {lab.completionCriteria.minimumPlacements} positions, including Identity & Access and Integration, to request review.</small>}</div><button className="primary-button" type="button" disabled={!minimumReady} onClick={review}>{state.attemptNumber ? "Review Again" : "Review Architecture"}</button></div></>}
    {state.phase === "review" && state.latestFeedback && <ReviewPanel feedback={state.latestFeedback} attemptNumber={state.attemptNumber} onRefine={() => onChange({ ...state, phase: "design" })} onCompare={() => onChange({ ...state, phase: "compare", referenceArchitectureViewed: true })} />}
    {state.phase === "compare" && <ReferenceComparison experience={experience} state={state} onContinue={() => onChange({ ...state, phase: "challenge" })} />}
    {state.phase === "challenge" && <section className="lab-challenge" aria-labelledby="lab-challenge-title"><p className="eyebrow">Apply</p><h2 id="lab-challenge-title">What would change if…</h2><p className="challenge-prompt">{lab.finalChallenge.prompt}</p><fieldset disabled={state.finalChallengeSubmitted}><legend>Choose one architectural response</legend>{lab.finalChallenge.options.map((option) => <label className="challenge-option" key={option.id}><input type="radio" name={lab.finalChallenge.id} checked={state.finalChallengeResponse === option.id} onChange={() => onChange({ ...state, finalChallengeResponse: option.id })} /><span>{option.label}</span></label>)}</fieldset>{!state.finalChallengeSubmitted ? <button className="primary-button" type="button" disabled={!state.finalChallengeResponse} onClick={() => onChange({ ...state, finalChallengeSubmitted: true })}>Review Response</button> : <div className="challenge-feedback" role="status"><p className="feedback-label">Architectural feedback</p><p>{challengeOption?.feedback}</p><button className="primary-button" type="button" onClick={() => onChange({ ...state, completed: true, phase: "complete" })}>Complete Architecture Lab</button></div>}</section>}
  </article>;
}

function ArchitectureSlots({ lab, state, onActivate, onRemove }: { lab: ArchitectureLabExperienceDefinition["lab"]; state: ArchitectureLabState; onActivate: (slotId: string) => void; onRemove: (slotId: string) => void }) {
  return <section className="lab-canvas" aria-labelledby="lab-canvas-title"><div className="lab-section-heading"><p className="eyebrow">My architecture</p><h2 id="lab-canvas-title">Select a position to configure</h2><p>The guided positions keep the system readable while you make each decision.</p></div><div className="lab-slot-list">{lab.slots.map((slot, index) => { const placement = state.placements.find((item) => item.slotId === slot.id); const component = lab.availableComponents.find((item) => item.id === placement?.componentId); const active = state.activeSlotId === slot.id; return <div className={`lab-slot is-${slot.zone} ${active ? "is-active" : ""}`} key={slot.id}><button type="button" aria-pressed={active} onClick={() => onActivate(slot.id)}><span className="slot-order">{String(index + 1).padStart(2, "0")}</span><span><strong>{slot.label}</strong><small>{component?.label ?? slot.placeholder}</small></span><span className="slot-state">{component ? "Configured" : "Select"}</span></button>{component && <button className="slot-remove" type="button" onClick={() => onRemove(slot.id)} aria-label={`Remove ${component.label} from ${slot.label}`}>Remove</button>}</div>; })}</div></section>;
}

function ReviewPanel({ feedback, attemptNumber, onRefine, onCompare }: { feedback: ArchitectureLabFeedback; attemptNumber: number; onRefine: () => void; onCompare: () => void }) {
  const groups = [{ title: "Strong decisions", items: feedback.strengths }, { title: "Consider", items: feedback.considerations }, { title: "Architectural gaps", items: feedback.gaps }, { title: "Next questions", items: feedback.nextQuestions }];
  return <section className="lab-feedback" aria-live="polite"><div className="lab-section-heading"><p className="eyebrow">Architecture review · Attempt {attemptNumber}</p><h2>Use the feedback to think and refine</h2><p>This deterministic educational review highlights tradeoffs and open questions. Another valid design may make different decisions.</p></div><div className="feedback-grid">{groups.filter((group) => group.items.length).map((group) => <section key={group.title}><h3>{group.title}</h3><ul>{group.items.map((item) => <li key={item}>{item}</li>)}</ul></section>)}</div><div className="lab-actions"><button className="secondary-button" type="button" onClick={onRefine}>Refine Architecture</button><button className="primary-button" type="button" onClick={onCompare}>Compare with Architect&apos;s Approach</button></div></section>;
}

function ReferenceComparison({ experience, state, onContinue }: { experience: ArchitectureLabExperienceDefinition; state: ArchitectureLabState; onContinue: () => void }) {
  const { lab } = experience; const label = (placement: ArchitectureLabPlacement) => lab.availableComponents.find((component) => component.id === placement.componentId)?.label;
  return <section className="lab-comparison" aria-labelledby="reference-title"><div className="lab-section-heading"><p className="eyebrow">Compare</p><h2 id="reference-title">{lab.referenceArchitecture.title}</h2><p>{lab.referenceArchitecture.summary}</p></div><div className="comparison-grid"><section><h3>My Architecture</h3><ul>{lab.slots.map((slot) => { const placement = state.placements.find((item) => item.slotId === slot.id); return <li key={slot.id}><span>{slot.label}</span><strong>{placement ? label(placement) : "Open consideration"}</strong></li>; })}</ul></section><section><h3>One Possible Approach</h3><ul>{lab.slots.map((slot) => { const placement = lab.referenceArchitecture.placements.find((item) => item.slotId === slot.id); return <li key={slot.id}><span>{slot.label}</span><strong>{placement ? label(placement) : "Open consideration"}</strong></li>; })}</ul></section></div><div className="reference-decisions"><h3>Major decisions</h3><ul>{lab.referenceArchitecture.decisions.map((decision) => <li key={decision}>{decision}</li>)}</ul></div><div className="lab-actions"><button className="primary-button" type="button" onClick={onContinue}>Apply to a New Challenge</button></div></section>;
}
