import type { MatchingActivityDefinition, MatchingResponse } from "../types";

export function CapabilityMatchingActivity({ definition, responses, activePromptId, reviewed, onActivePromptChange, onResponsesChange, onReview, onContinue }: { definition: MatchingActivityDefinition; responses: MatchingResponse[]; activePromptId: string | null; reviewed: boolean; onActivePromptChange: (promptId: string) => void; onResponsesChange: (responses: MatchingResponse[]) => void; onReview: () => void; onContinue: () => void }) {
  const assign = (itemId: string) => {
    if (!activePromptId || reviewed) return;
    onResponsesChange([...responses.filter((response) => response.promptId !== activePromptId && response.itemId !== itemId), { promptId: activePromptId, itemId }]);
  };
  const allMatched = responses.length === definition.prompts.length;

  return <section className="capability-matching" aria-labelledby="matching-title"><div className="lab-section-heading"><p className="eyebrow">Capability matching</p><h2 id="matching-title">{definition.title}</h2><p>{definition.introduction}</p></div><p className="matching-instruction">{reviewed ? "Review the educational feedback, then continue when ready." : activePromptId ? "Now choose the responsibility that belongs with the selected capability." : "Select an architecture capability, then choose its responsibility."}</p><div className="matching-columns"><section aria-labelledby="capability-column-title"><h3 id="capability-column-title">Architecture Capability</h3><div className="matching-card-list">{definition.prompts.map((prompt, index) => { const response = responses.find((item) => item.promptId === prompt.id); const isActive = activePromptId === prompt.id; const matchedWell = response?.itemId === prompt.matchingItemId; return <button className={`matching-card capability-card ${isActive ? "is-active" : ""}`} type="button" key={prompt.id} disabled={reviewed} aria-pressed={isActive} onClick={() => onActivePromptChange(prompt.id)}><span className="matching-index">{String(index + 1).padStart(2, "0")}</span><span><strong>{prompt.label}</strong>{prompt.context && <small>{prompt.context}</small>}{response && <em>Paired with responsibility {String(definition.items.findIndex((item) => item.id === response.itemId) + 1).padStart(2, "0")}</em>}{reviewed && <b>{matchedWell ? "Matched well" : "Reconsider this pairing — think about what this capability is responsible for."}</b>}</span></button>; })}</div></section><section aria-labelledby="responsibility-column-title"><h3 id="responsibility-column-title">Architectural Role / Responsibility</h3><div className="matching-card-list">{definition.items.map((item, index) => { const response = responses.find((entry) => entry.itemId === item.id); const selected = Boolean(response); return <button className={`matching-card responsibility-card ${selected ? "is-paired" : ""}`} type="button" key={item.id} disabled={reviewed || !activePromptId} aria-pressed={selected} onClick={() => assign(item.id)}><span className="matching-index">{String(index + 1).padStart(2, "0")}</span><span><strong>{item.description}</strong>{response && <em>Paired with capability {String(definition.prompts.findIndex((prompt) => prompt.id === response.promptId) + 1).padStart(2, "0")}</em>}</span></button>; })}</div></section></div><div className="matching-actions" aria-live="polite"><span>{responses.length} of {definition.prompts.length} pairs completed</span>{reviewed ? <button className="primary-button" type="button" onClick={onContinue}>Continue to Architecture Builder</button> : <button className="primary-button" type="button" disabled={!allMatched} onClick={onReview}>Review Matches</button>}</div></section>;
}
