"use client";

import type { ArchitectureLabExperienceDefinition } from "@/modules/learning-experience/types";
import { ArchitectingAiIcon } from "@/components/icons";
import { reviewArchitectureLab } from "../review-architecture-lab";
import type { ArchitectureLabState } from "../types";
import { ArchitectureToolkit } from "./architecture-toolkit";

const stages = ["Understand the Mission", "Classify the Information", "Build the Architecture", "Follow Two Requests", "Architecture Change Request", "Enterprise Reality Test", "Architecture Review", "Explain Your Architecture", "Architect’s Reference", "Lab Completion"];
const classificationItems = [
  { id: "leave-policy", label: "HR leave policy", preferred: "knowledge" },
  { id: "holiday-policy", label: "Holiday policy", preferred: "knowledge" },
  { id: "leave-balance", label: "Employee’s current leave balance", preferred: "systems" },
  { id: "employee-identity", label: "Employee identity", preferred: "identity" },
];
const classificationDestinations = [{ id: "knowledge", label: "Knowledge Sources" }, { id: "systems", label: "Enterprise Systems / APIs" }, { id: "identity", label: "Identity & Context" }];
const changeConcerns = ["stronger authorization", "controlled transaction APIs", "business-rule validation", "audit trail", "failure/recovery behavior", "approval or human/system control where appropriate", "monitoring", "AI output/action boundaries"].map((label, index) => ({ id: `change-${index + 1}`, label }));
const realityScenarios = [
  { id: "provider", scenario: "The LLM provider becomes temporarily unavailable.", preferred: "resilience", options: [{ id: "resilience", label: "Reliability / Resilience" }, { id: "identity", label: "Identity design" }, { id: "freshness", label: "Knowledge freshness" }], feedback: "The workload needs an appropriate response to dependency failure, such as graceful degradation, recovery behavior, or an alternate service path where requirements justify it." },
  { id: "outdated", scenario: "HR policy documents are updated, but the AI continues using outdated information.", preferred: "freshness", options: [{ id: "latency", label: "Response latency" }, { id: "freshness", label: "Knowledge lifecycle / freshness / operational controls" }, { id: "scale", label: "User scale" }], feedback: "The knowledge lifecycle must make approved updates available and provide visibility into freshness and ingestion behavior." },
  { id: "access", scenario: "An employee attempts to retrieve another employee’s leave balance.", preferred: "authorization", options: [{ id: "authorization", label: "Identity / Authorization / Data-access enforcement" }, { id: "retrieval", label: "Retrieval quality" }, { id: "cost", label: "Cost management" }], feedback: "Identity must be established and authorization enforced at the relevant application, integration, and data-access boundaries." },
  { id: "cost", scenario: "AI usage doubles and monthly cost rises significantly.", preferred: "cost", options: [{ id: "governance", label: "Document governance" }, { id: "cost", label: "Cost management / usage visibility / optimization" }, { id: "identity", label: "Identity federation" }], feedback: "Usage and cost visibility support informed optimization and capacity decisions without assuming one universal target." },
];

export function ProductionArchitectureLabExperience({ experience, state, onChange }: { experience: ArchitectureLabExperienceDefinition; state: ArchitectureLabState; onChange: (state: ArchitectureLabState) => void }) {
  const { lab } = experience;
  const stage = state.currentStage;
  const setStage = (currentStage: number) => onChange({ ...state, currentStage });
  const assign = (componentId: string) => { if (!state.activeSlotId) return; onChange({ ...state, placements: [...state.placements.filter((placement) => placement.slotId !== state.activeSlotId), { slotId: state.activeSlotId, componentId }] }); };
  const minimumReady = state.placements.length >= lab.completionCriteria.minimumPlacements && lab.completionCriteria.requiredSlotIds.every((slotId) => state.placements.some((placement) => placement.slotId === slotId));
  const stageReady = [Boolean(state.missionResponse), Object.keys(state.informationClassifications).length === classificationItems.length, minimumReady, Boolean(state.requestFlowResponse), state.changeRequestSubmitted, Object.keys(state.realityTestResponses).length === realityScenarios.length, Boolean(state.latestFeedback), state.learnerExplanation.trim().length >= 20, state.referenceArchitectureViewed, state.completed][stage];
  const next = () => {
    if (!stageReady || stage >= stages.length - 1) return;
    const nextStage = stage + 1;
    if (nextStage === 6) {
      const feedback = reviewArchitectureLab(lab, state.placements);
      const attemptNumber = state.attemptNumber + 1;
      onChange({ ...state, currentStage: nextStage, attemptNumber, latestFeedback: feedback, reviewHistory: [...state.reviewHistory, { attemptNumber, placements: state.placements.map((placement) => ({ ...placement })), feedback }] });
    } else if (nextStage === 8) onChange({ ...state, currentStage: nextStage, referenceArchitectureViewed: true });
    else onChange({ ...state, currentStage: nextStage });
  };

  return <article className="experience-surface architecture-lab production-architecture-lab"><header className="experience-heading"><p className="eyebrow">Architecture Lab 01 · Guided Foundation Lab</p><h1 tabIndex={-1}>Architecture Lab 01</h1><p className="lab-subtitle">Design Your First Enterprise AI Architecture</p><p>Translate business requirements into a high-level Enterprise AI architecture and explain why the major architecture capabilities are needed.</p><small>Approximately 15–25 minutes · No timer</small></header>
    <div className="production-lab-shell"><nav className="lab-stage-navigator" aria-label="Architecture Lab stages"><p aria-live="polite">Step {stage + 1} of {stages.length}</p><ol>{stages.map((label, index) => <li key={label}><button type="button" disabled={index > stage} aria-current={index === stage ? "step" : undefined} onClick={() => setStage(index)}><span>{index < stage ? <ArchitectingAiIcon name="complete" size={17} /> : index + 1}</span><strong>{label}</strong><small>{index < stage ? "Visited" : index === stage ? "Current" : "Upcoming"}</small></button></li>)}</ol></nav>
      <div className="lab-stage-workspace" aria-live="polite">
        {stage === 0 && <MissionStage state={state} onChange={onChange} />}
        {stage === 1 && <ClassificationStage state={state} onChange={onChange} />}
        {stage === 2 && <BuilderStage experience={experience} state={state} onChange={onChange} onAssign={assign} minimumReady={minimumReady} />}
        {stage === 3 && <RequestsStage state={state} onChange={onChange} />}
        {stage === 4 && <ChangeStage state={state} onChange={onChange} />}
        {stage === 5 && <RealityStage state={state} onChange={onChange} />}
        {stage === 6 && <ReviewStage state={state} />}
        {stage === 7 && <ExplanationStage state={state} onChange={onChange} />}
        {stage === 8 && <ReferenceStage experience={experience} state={state} />}
        {stage === 9 && <CompletionStage state={state} onChange={onChange} />}
        {stage < 9 && <div className="production-lab-controls"><button className="secondary-button" type="button" disabled={stage === 0} onClick={() => setStage(stage - 1)}>Previous</button><span>Step {stage + 1} of 10</span><button className="primary-button" type="button" disabled={!stageReady} onClick={next}>Next</button></div>}
      </div></div>
  </article>;
}

function StageHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <header className="lab-stage-heading"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</header>; }

function MissionStage({ state, onChange }: { state: ArchitectureLabState; onChange: (state: ArchitectureLabState) => void }) {
  const options = [{ id: "chatbot", label: "A. A chatbot" }, { id: "llm", label: "B. An LLM application" }, { id: "workload", label: "C. An enterprise AI workload" }, { id: "search", label: "D. A document search engine" }];
  return <section><StageHeading eyebrow="Start Architecture Lab" title="Your Assignment"><p>You are the Enterprise AI Architect for a large organization. HR wants to introduce an AI-powered Employee Assistant. Your task is to turn the business request into an architecture that could realistically operate inside an enterprise.</p></StageHeading><div className="architecture-brief"><section><h3>Business Request</h3><p>Employees should be able to:</p><ul><li>ask questions about HR policies</li><li>find relevant policy information</li><li>check their current leave balance</li><li>receive answers appropriate to their identity and permissions</li></ul></section><section><h3>Enterprise Context</h3><dl><div><dt>Users</dt><dd>Approximately 10,000 employees</dd></div><div><dt>Access</dt><dd>Existing enterprise identity</dd></div><div><dt>Knowledge</dt><dd>HR policies and internal documents</dd></div><div><dt>Live Data</dt><dd>Employee leave information</dd></div><div><dt>Sensitivity</dt><dd>Employee-specific information</dd></div><div><dt>Availability</dt><dd>Business-critical employee service</dd></div><div><dt>Rollout</dt><dd>Controlled production deployment</dd></div></dl></section></div><fieldset className="lab-radio-cards"><legend>What are you actually architecting?</legend>{options.map((option) => <label className={state.missionResponse === option.id ? "is-selected" : ""} key={option.id}><input type="radio" name="mission-response" checked={state.missionResponse === option.id} onChange={() => onChange({ ...state, missionResponse: option.id })} /><span>{option.label}</span></label>)}</fieldset>{state.missionResponse && <div className="lab-educational-feedback" role="status"><strong>{state.missionResponse === "workload" ? "Preferred framing" : "Consider the complete workload"}</strong><p>The solution includes AI, but the workload also depends on identity, application logic, enterprise knowledge, live HR data, authorization, security, monitoring and operations.</p></div>}</section>;
}

function ClassificationStage({ state, onChange }: { state: ArchitectureLabState; onChange: (state: ArchitectureLabState) => void }) {
  return <section><StageHeading eyebrow="Stage 2" title="Classify the Information"><p>Choose the most appropriate architectural source or context for each item.</p></StageHeading><div className="classification-list">{classificationItems.map((item) => { const selected = state.informationClassifications[item.id]; return <label key={item.id}><strong>{item.label}</strong><select value={selected ?? ""} onChange={(event) => onChange({ ...state, informationClassifications: { ...state.informationClassifications, [item.id]: event.target.value } })}><option value="" disabled>Select a destination</option>{classificationDestinations.map((destination) => <option value={destination.id} key={destination.id}>{destination.label}</option>)}</select>{selected && <small>{selected === item.preferred ? "Defensible classification" : "Revisit whether this is knowledge, a current business fact, or identity context."}</small>}</label>; })}</div>{Object.keys(state.informationClassifications).length === classificationItems.length && <div className="lab-educational-feedback" role="status"><p>Not every enterprise question should be answered from indexed documents or a retrieval pipeline. Current employee-specific information may need to come from an authoritative enterprise system.</p></div>}</section>;
}

function BuilderStage({ experience, state, onChange, onAssign, minimumReady }: { experience: ArchitectureLabExperienceDefinition; state: ArchitectureLabState; onChange: (state: ArchitectureLabState) => void; onAssign: (id: string) => void; minimumReady: boolean }) {
  const { lab } = experience;
  return <section><StageHeading eyebrow="Stage 3" title="Build the Architecture"><p>Select a conceptual zone, then assign a compatible component from the toolkit. You can refine placements before continuing.</p></StageHeading><div className="production-builder"><section className="production-lab-canvas" aria-labelledby="production-canvas-title"><h3 id="production-canvas-title">My Architecture</h3>{lab.slots.map((slot) => { const placement = state.placements.find((item) => item.slotId === slot.id); const component = lab.availableComponents.find((item) => item.id === placement?.componentId); return <div className={`production-slot is-${slot.zone} ${state.activeSlotId === slot.id ? "is-active" : ""}`} key={slot.id}><button type="button" aria-pressed={state.activeSlotId === slot.id} onClick={() => onChange({ ...state, activeSlotId: slot.id })}><span><strong>{slot.label}</strong><small>{slot.description}</small></span><b>{component?.label ?? "Select a component"}</b></button>{component && <button type="button" className="slot-remove" onClick={() => onChange({ ...state, placements: state.placements.filter((item) => item.slotId !== slot.id) })}>Remove</button>}</div>; })}</section><ArchitectureToolkit components={lab.availableComponents} placements={state.placements} activeSlotId={state.activeSlotId} onAssign={onAssign} /></div><p className="builder-readiness" role="status">{state.placements.length} of {lab.slots.length} zones configured. {minimumReady ? "Architecture ready to explore." : "Configure at least 8 zones, including identity, integration, enterprise systems and operations."}</p></section>;
}

function Flow({ nodes }: { nodes: string[] }) { return <ol className="production-request-flow">{nodes.map((node, index) => <li key={`${index}-${node}`}>{node}</li>)}</ol>; }
function RequestsStage({ state, onChange }: { state: ArchitectureLabState; onChange: (state: ArchitectureLabState) => void }) {
  const options = [{ id: "slow", label: "A. The model is too slow" }, { id: "authoritative", label: "B. The answer is employee-specific and should come from an appropriate authoritative current source" }, { id: "numbers", label: "C. Documents cannot contain numbers" }, { id: "no-rag", label: "D. RAG cannot be used in enterprises" }];
  return <section><StageHeading eyebrow="Stage 4" title="Follow Two Requests"><p>Trace how two different information needs may use different parts of the architecture.</p></StageHeading><article className="request-path-card"><h3>Request A</h3><blockquote>“What is the company’s parental leave policy?”</blockquote><Flow nodes={["Employee", "Identity", "Application", "Retrieval / Knowledge", "Approved HR Policy Source", "AI / Response", "Employee"]} /><p>This is primarily a knowledge-retrieval and response-generation scenario. The exact path depends on the workload.</p></article><article className="request-path-card"><h3>Request B</h3><blockquote>“How many annual-leave days do I have remaining?”</blockquote><Flow nodes={["Employee", "Identity", "Authorization", "Application", "HR API / Integration", "HR System of Record", "Response generation where useful", "Employee"]} /></article><fieldset className="lab-radio-cards"><legend>Why should the system not simply answer this from indexed documents?</legend>{options.map((option) => <label className={state.requestFlowResponse === option.id ? "is-selected" : ""} key={option.id}><input type="radio" name="request-source" checked={state.requestFlowResponse === option.id} onChange={() => onChange({ ...state, requestFlowResponse: option.id })} /><span>{option.label}</span></label>)}</fieldset>{state.requestFlowResponse && <div className="lab-educational-feedback" role="status"><strong>{state.requestFlowResponse === "authoritative" ? "Preferred reasoning" : "Reconsider the source of the current business fact"}</strong><p>The current leave balance is an employee-specific transactional fact. A generative model may help interpret or present the answer, but the value should come from an appropriate authoritative enterprise source.</p></div>}</section>;
}

function ChangeStage({ state, onChange }: { state: ArchitectureLabState; onChange: (state: ArchitectureLabState) => void }) {
  const toggle = (id: string) => onChange({ ...state, changeRequestConcerns: state.changeRequestConcerns.includes(id) ? state.changeRequestConcerns.filter((item) => item !== id) : [...state.changeRequestConcerns, id] });
  return <section><StageHeading eyebrow="Stage 5 · New Requirement" title="Architecture Change Request"><blockquote>“Employees should also be able to request a change to their bank details.”</blockquote></StageHeading><form onSubmit={(event) => { event.preventDefault(); onChange({ ...state, changeRequestSubmitted: true }); }}><fieldset className="lab-checkbox-cards" disabled={state.changeRequestSubmitted}><legend>Which architectural concerns would you revisit?</legend>{changeConcerns.map((concern) => <label className={state.changeRequestConcerns.includes(concern.id) ? "is-selected" : ""} key={concern.id}><input type="checkbox" checked={state.changeRequestConcerns.includes(concern.id)} onChange={() => toggle(concern.id)} /><span>{concern.label}</span></label>)}</fieldset>{!state.changeRequestSubmitted && <button className="primary-button" type="submit" disabled={!state.changeRequestConcerns.length}>Review Change Impact</button>}</form>{state.changeRequestSubmitted && <><div className="lab-educational-feedback" role="status"><strong>Moving from read-only information access to business actions changes the risk profile.</strong><p>The architecture now needs to consider not only what information the user may see, but which actions the user or AI-enabled application is permitted to initiate.</p><p>Human approval is not automatically required for every transaction. Appropriate controls depend on the business process, policy and risk.</p></div><div className="read-action-comparison"><section><h3>Read</h3><Flow nodes={["User", "AI workload", "Retrieve information", "Answer"]} /></section><section><h3>Action</h3><Flow nodes={["User", "Identity + Authorization", "Application / AI", "Validate intent", "Controlled Business API", "Business rules / controls", "System of record", "Audit + Monitoring"]} /></section></div><aside className="lab-architect-insight"><p className="eyebrow">Architect Insight</p><blockquote>Allowing an AI-enabled system to retrieve information and allowing it to initiate a business transaction are different architecture problems.</blockquote></aside></>}</section>;
}

function RealityStage({ state, onChange }: { state: ArchitectureLabState; onChange: (state: ArchitectureLabState) => void }) {
  const scenario = realityScenarios[state.currentRealityScenario]; const response = state.realityTestResponses[scenario.id]; const isLast = state.currentRealityScenario === realityScenarios.length - 1;
  return <section><StageHeading eyebrow="Stage 6" title="Enterprise Reality Test"><p>Consider one operational scenario at a time. This is educational feedback, not a score.</p></StageHeading><article className="reality-scenario"><p className="eyebrow">Scenario {state.currentRealityScenario + 1} of {realityScenarios.length}</p><blockquote>“{scenario.scenario}”</blockquote><fieldset className="lab-radio-cards"><legend>Which architecture quality is being tested?</legend>{scenario.options.map((option) => <label className={response === option.id ? "is-selected" : ""} key={option.id}><input type="radio" name={`reality-${scenario.id}`} checked={response === option.id} onChange={() => onChange({ ...state, realityTestResponses: { ...state.realityTestResponses, [scenario.id]: option.id } })} /><span>{option.label}</span></label>)}</fieldset>{response && <div className="lab-educational-feedback" role="status"><strong>{response === scenario.preferred ? "Strong connection" : "Consider the primary quality under pressure"}</strong><p>{scenario.feedback}</p></div>}<div className="reality-controls"><button className="secondary-button" type="button" disabled={state.currentRealityScenario === 0} onClick={() => onChange({ ...state, currentRealityScenario: state.currentRealityScenario - 1 })}>Previous Scenario</button><button className="primary-button" type="button" disabled={!response || isLast} onClick={() => onChange({ ...state, currentRealityScenario: state.currentRealityScenario + 1 })}>Next Scenario</button></div></article></section>;
}

function ReviewStage({ state }: { state: ArchitectureLabState }) {
  const feedback = state.latestFeedback; if (!feedback) return null;
  const categories = [
    ["Business Alignment", feedback.strengths.find((item) => item.includes("Business")) ?? "Consider: make the business use cases and users explicit."],
    ["Identity & Access", feedback.strengths.find((item) => item.includes("identity")) ?? "Architectural gap: clarify identity and access boundaries."],
    ["Knowledge Architecture", feedback.strengths.find((item) => item.includes("Policy")) ?? "Consider: separate approved policy knowledge from current transactional data."],
    ["Enterprise Integration", feedback.strengths.find((item) => item.includes("Authoritative")) ?? "Architectural gap: include controlled access to authoritative HR information."],
    ["Security & Governance", feedback.strengths.find((item) => item.includes("security")) ?? "Consider: represent cross-cutting security and governance."],
    ["Operations", feedback.strengths.find((item) => item.includes("Monitoring")) ?? "Operational consideration: include reliability, monitoring and cost visibility."],
    ["Action Safety", state.changeRequestSubmitted ? "Strong decision: transactional capabilities require additional control compared with read-only access." : "Consider: revisit controls when the workload can initiate actions."],
  ];
  return <section><StageHeading eyebrow="Stage 7 · Deterministic review" title="Architecture Review"><p>This rule-based review highlights defensible decisions and open considerations. It does not assign a score, pass, or fail.</p></StageHeading><div className="production-review" role="status">{categories.map(([title, text]) => <section key={title}><h3>{title}</h3><p>{text}</p></section>)}</div></section>;
}

function ExplanationStage({ state, onChange }: { state: ArchitectureLabState; onChange: (state: ArchitectureLabState) => void }) { return <section><StageHeading eyebrow="Stage 8" title="Explain Your Architecture"><p>Consider users, authoritative data, AI, integration, security and operations.</p></StageHeading><label className="architecture-explanation" htmlFor="architecture-explanation"><strong>In 2–4 sentences, explain why your architecture is suitable for this HR Assistant.</strong><textarea id="architecture-explanation" rows={7} value={state.learnerExplanation} onChange={(event) => onChange({ ...state, learnerExplanation: event.target.value })} /><small>Your response remains transient and is not AI-evaluated. Enter a meaningful non-empty response to continue.</small></label></section>; }

function ReferenceStage({ experience, state }: { experience: ArchitectureLabExperienceDefinition; state: ArchitectureLabState }) {
  const { lab } = experience; const label = (componentId: string) => lab.availableComponents.find((component) => component.id === componentId)?.label;
  return <section><StageHeading eyebrow="Stage 9 · Architect’s Reference" title="One Defensible Architecture"><p>{lab.referenceArchitecture.summary}</p></StageHeading><div className="reference-comparison"><section><h3>My Architecture</h3><ul>{lab.slots.map((slot) => { const placement = state.placements.find((item) => item.slotId === slot.id); return <li key={slot.id}><span>{slot.label}</span><strong>{placement ? label(placement.componentId) : "Open consideration"}</strong></li>; })}</ul></section><section><h3>One Defensible Architecture</h3><ul>{lab.slots.map((slot) => { const placement = lab.referenceArchitecture.placements.find((item) => item.slotId === slot.id); return <li key={slot.id}><span>{slot.label}</span><strong>{placement ? label(placement.componentId) : "Open consideration"}</strong></li>; })}</ul></section></div><div className="reference-path"><Flow nodes={["Employee", "Enterprise Identity", "Employee Portal", "Application / Orchestrator", "AI + Knowledge + HR Integration", "Authorized Response"]} /><p><strong>Cross-cutting:</strong> Identity · Security · Governance</p><p><strong>Operational:</strong> Observability · Operations · Cost</p></div></section>;
}

function CompletionStage({ state, onChange }: { state: ArchitectureLabState; onChange: (state: ArchitectureLabState) => void }) {
  return <section><StageHeading eyebrow="Stage 10" title="Architecture Lab 01 — Complete"><p>You started with a business request and developed it into an enterprise architecture.</p><p>You distinguished enterprise knowledge from live system data, considered identity and authorization, connected AI to enterprise systems, evaluated operational risks, and adapted the architecture when the business requirement changed.</p></StageHeading><aside className="lab-architect-insight"><p className="eyebrow">Architect Takeaway</p><blockquote>Enterprise AI architecture is not the arrangement of AI components.{"\n\n"}It is the deliberate design of the complete system in which AI operates.</blockquote></aside><button className="primary-button" type="button" onClick={() => onChange({ ...state, completed: true, phase: "complete" })}>Continue to Experience 10</button></section>;
}
