"use client";

import { useMemo, useState } from "react";
import { architectureDomainContent, architectureNodePositions, enterpriseAiArchitecture } from "../enterprise-ai-example";
import { getRelatedArchitectureIds } from "../utils/selection";

interface Props { selectedDomainId: string | null; onSelectedDomainChange: (domainId: string) => void; }

export function EnterpriseArchitectureExplorer({ selectedDomainId, onSelectedDomainChange }: Props) {
  const [hoveredDomainId, setHoveredDomainId] = useState<string | null>(null);
  const activeDomainId = hoveredDomainId ?? selectedDomainId;
  const related = useMemo(() => getRelatedArchitectureIds(enterpriseAiArchitecture, activeDomainId), [activeDomainId]);
  const selectedNode = enterpriseAiArchitecture.nodes.find((node) => node.id === selectedDomainId);
  const selectedContent = architectureDomainContent.find((item) => item.domainId === (selectedNode?.domainId ?? selectedDomainId));
  const positionByNode = new Map(architectureNodePositions.map((position) => [position.nodeId, position]));
  return <div className="explorer-layout"><div className="architecture-canvas" aria-label="Interactive enterprise AI architecture"><div className="architecture-legend"><span><i className="legend-line" /> Relationship</span><span><i className="legend-cross" /> Cross-cutting control</span></div><div className="architecture-map"><svg className="architecture-connectors" viewBox="0 0 770 700" aria-hidden="true"><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" /></marker></defs>{enterpriseAiArchitecture.relationships.map((relationship) => { const source = positionByNode.get(relationship.sourceNodeId); const target = positionByNode.get(relationship.targetNodeId); if (!source || !target) return null; const x1 = source.x + source.width / 2; const y1 = source.y + source.height / 2; const x2 = target.x + target.width / 2; const y2 = target.y + target.height / 2; const highlighted = related.relationshipIds.has(relationship.id); return <path key={relationship.id} d={`M ${x1} ${y1} C ${x1} ${(y1 + y2) / 2}, ${x2} ${(y1 + y2) / 2}, ${x2} ${y2}`} className={highlighted ? "connector is-highlighted" : activeDomainId ? "connector is-subdued" : "connector"} markerEnd="url(#arrow)" />; })}</svg>{enterpriseAiArchitecture.nodes.map((node) => { const position = positionByNode.get(node.id); if (!position) return null; const isSelected = node.id === selectedDomainId || (!selectedNode && node.domainId === selectedDomainId); const isRelated = related.nodeIds.has(node.id); const stateClass = isSelected ? "is-selected" : activeDomainId && !isRelated ? "is-subdued" : isRelated ? "is-related" : ""; return <button key={node.id} type="button" className={`architecture-node ${node.crossCutting ? "is-cross-cutting" : ""} ${stateClass}`} style={{ left: `${position.x / 7.7}%`, top: `${position.y / 7}%`, width: `${position.width / 7.7}%`, height: `${position.height / 7}%` }} aria-pressed={isSelected} aria-label={`${node.label}. ${node.description}`} onClick={() => onSelectedDomainChange(node.id)} onMouseEnter={() => setHoveredDomainId(node.id)} onMouseLeave={() => setHoveredDomainId(null)} onFocus={() => setHoveredDomainId(node.id)} onBlur={() => setHoveredDomainId(null)}><span>{node.label}</span>{isSelected && <span className="selected-indicator">Selected</span>}</button>; })}</div></div><aside className="architecture-panel" aria-live="polite">{selectedContent ? <><p className="eyebrow">{selectedContent.eyebrow}</p><h3>{selectedContent.title}</h3><p>{selectedContent.summary}</p><ul>{selectedContent.points.map((point) => <li key={point}>{point}</li>)}</ul></> : <><p className="eyebrow">Explore the system</p><h3>Select an architecture domain</h3><p>Choose any domain to trace its relationships. Nothing disappears; the connected system stays visible.</p><p className="panel-hint">Tip: use Tab and Enter to explore with a keyboard.</p></>}</aside></div>;
}
