"use client";

import Link from "next/link";
import { useState } from "react";

const lessonRoute = "/workshops/enterprise-ai-foundations/from-ai-solution-to-enterprise-ai-architecture";
const labRoute = "/workshops/enterprise-ai-foundations/demo-learning-experience";
const curriculum = [
  { part: "Part I", title: "Think Like an Architect", lessons: ["From AI Solution to Enterprise AI Architecture", "How Enterprise AI Architects Think"] },
  { part: "Part II", title: "Build the Intelligence", lessons: ["AI Foundations for Enterprise Architects", "Foundation Models, Prompting & Context Engineering", "Enterprise Data for AI", "Embeddings, Vector Search & RAG", "Agents, Tools & AI Orchestration", "Enterprise Integration & APIs", "Identity, Security & AI Guardrails", "AI Governance, Risk & Responsible AI", "Observability, LLMOps & Production Operations"] },
  { part: "Part III", title: "Architect the Enterprise", lessons: ["Designing an End-to-End Enterprise RAG Architecture", "Designing Enterprise Agentic AI Architecture", "Architecture Patterns, Trade-offs & Technology Decisions", "Scaling Enterprise AI: Platform Architecture", "Enterprise AI Architecture Capstone"] },
];
const lessonCopy = [
  "Understand why a working AI application is not automatically enterprise-ready and explore core architectural capabilities.",
  "Learn how business outcomes, requirements and trade-offs shape architecture decisions.",
  "Understand the AI foundations enterprise architects need.",
];

function Brand() { return <Link className="home-brand" href="/" aria-label="Architecting AI home"><span className="home-brand-mark" aria-hidden="true">A</span><span>Architecting AI</span></Link>; }

function ArchitectureVisual() {
  const domains = [{ label:"Business Outcomes", icon:"target" }, { label:"Enterprise Data", icon:"database" }, { label:"AI & Intelligence", icon:"brain" }, { label:"Integration", icon:"link" }, { label:"Security & Governance", icon:"shield" }, { label:"Observability & Operations", icon:"monitor" }];
  return <figure className="hero-architecture" aria-labelledby="architecture-caption"><div className="architecture-network" aria-hidden="true"><div className="perspective-grid" /><div className="architecture-connectors">{domains.map((domain,index) => <i className={`domain-connector domain-connector-${index+1}`} key={domain.label} />)}</div><div className="architecture-core">{["Operations", "Integration", "Enterprise Data", "Orchestration", "AI"].map((label,index) => <div className={`stack-layer stack-layer-${index+1}`} key={label}><span>{label}</span></div>)}</div>{domains.map((domain,index) => <div className={`domain-node domain-node-${index+1}`} key={domain.label}><b className={`domain-icon icon-${domain.icon}`}><i /></b><span>{domain.label}</span></div>)}</div><figcaption id="architecture-caption">A learning model for reasoning about connected enterprise concerns — not a mandatory technology stack.</figcaption></figure>;
}

function LessonCard({ number, title, copy }: { number: number; title: string; copy: string }) {
  const content = <><div className="lesson-meta"><span>Lesson {number}</span><span className={number === 1 ? "status active" : "status"}>{number === 1 ? "In Development" : "Coming Soon"}</span></div><div className={`lesson-icon lesson-icon-${number}`} aria-hidden="true">{["⌂","◎","▤"][number-1]}</div><h3>{title}</h3><p>{copy}</p><div className="lesson-card-footer"><span>{number === 1 ? "In Development" : "Coming Soon"}</span><small>{number === 1 ? "Experiences 1–6 available" : "Not Started"}</small></div></>;
  return number === 1 ? <Link className="journey-card" href={lessonRoute}>{content}</Link> : <article className="journey-card">{content}</article>;
}

export function PublicHomepage() {
  const [expanded, setExpanded] = useState(false);
  const toggle = () => setExpanded((value) => !value);
  const controlLabel = expanded ? "Collapse 16-lesson learning journey" : "Show all 16 lessons";
  return <div className="public-home" id="top">
    <header className="public-header"><Brand /><nav aria-label="Primary navigation"><a href="#learning-journey">Learning Journey</a><Link href={labRoute}>Architecture Lab</Link><a href="#resources">Resources</a><a href="#about">About</a></nav><Link className="header-sign-in" href="/login"><span aria-hidden="true">♙</span> Sign In</Link></header>
    <main>
      <section className="home-hero"><div className="hero-inner"><div className="hero-copy"><p className="home-eyebrow">Enterprise AI Learning Studio</p><h1>Architecting AI</h1><p className="hero-lede">Master the art and science of designing, building, and operating enterprise AI solutions that deliver real business value.</p><div className="value-grid">{[["▱","16 Comprehensive Lessons","From foundations to advanced architectural patterns"],["△","Hands-on Architecture Labs","Apply concepts with practical exercises and scenarios"],["⌾","Enterprise Focused","Learn principles, trade-offs and sound practices"]].map(([icon,title,copy]) => <div className="hero-value" key={title}><span aria-hidden="true">{icon}</span><div><strong>{title}</strong><p>{copy}</p></div></div>)}</div><div className="hero-actions"><Link className="home-button primary" href="/workshops/enterprise-ai-foundations">Start Learning <span aria-hidden="true">→</span></Link><Link className="home-button secondary-dark" href={labRoute}>Explore Architecture Lab <span aria-hidden="true">△</span></Link></div></div><ArchitectureVisual /></div></section>
      <section className="home-section journey-section" id="learning-journey"><div className="journey-layout"><div className="journey-intro"><p className="home-eyebrow">The curriculum</p><h2>Your Learning Journey</h2><p>A structured path from understanding AI solutions to architecting enterprise-ready AI systems.</p><div className="journey-controls"><button className="text-control" type="button" onClick={toggle} aria-expanded={expanded} aria-controls="complete-curriculum">{expanded ? "Collapse Learning Journey" : "View Full Learning Journey"} <span aria-hidden="true">{expanded ? "↑" : "→"}</span></button><button className="journey-expander" type="button" onClick={toggle} aria-expanded={expanded} aria-controls="complete-curriculum" aria-label={controlLabel}><span aria-hidden="true">{expanded ? "−" : "+"}</span><b>{expanded ? "Collapse learning journey" : "Explore all 16 lessons"}</b></button></div><Link className="workshops-context-link" href="/workshops">Explore Workshops <span aria-hidden="true">→</span></Link></div>{!expanded && <div className="journey-preview">{curriculum.flatMap((part) => part.lessons).slice(0,3).map((title,index) => <LessonCard key={title} number={index+1} title={title} copy={lessonCopy[index]} />)}</div>}</div>
        <div id="complete-curriculum" className={`complete-curriculum ${expanded ? "is-expanded" : ""}`} aria-hidden={!expanded}>{expanded && curriculum.map((group, groupIndex) => { const start = curriculum.slice(0,groupIndex).reduce((sum,item) => sum + item.lessons.length,0); return <section className="curriculum-part" key={group.part}><header><span>{group.part}</span><h3>{group.title}</h3></header><div className="curriculum-list">{group.lessons.map((title,index) => { const number=start+index+1; return <div className="curriculum-row" key={title}><span>{String(number).padStart(2,"0")}</span><div><strong>{title}</strong><small>{number === 1 ? "In Development" : "Coming Soon"}</small></div>{number === 1 && <Link href={lessonRoute} aria-label={`Open Lesson 1: ${title}`}>Open <span aria-hidden="true">→</span></Link>}</div>})}</div></section>})}</div>
      </section>
      <section className="principles-section"><div className="principles-heading"><p className="home-eyebrow">How you will learn</p><h2>Built for architecture practice</h2></div><div className="principles-grid">{[["01","Enterprise Focused","Real-world scenarios and enterprise-grade architecture thinking."],["02","Hands-on Learning","Architecture labs, decisions and exercises reinforce concepts."],["03","Vendor Neutral","Principles and trade-offs that apply across platforms."],["04","Source-Informed","Theory checked against authoritative primary guidance."]].map(([number,title,copy]) => <article key={title}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
      <section className="mission-callout"><div><p className="home-eyebrow">A three-minute introduction</p><h2>Experience Architecting AI</h2><p>Try a short interactive architecture workshop before creating an account.</p><div className="mission-reassurance">3 Minutes <span>•</span> Interactive <span>•</span> No Registration Required</div></div><Link className="home-button primary" href="/experience/mission-zero">Experience Mission Zero <span aria-hidden="true">→</span></Link></section>
      <section className="reference-band" id="resources"><div><p className="home-eyebrow">Reference sources</p><h2>Authoritative References</h2><p>The curriculum uses vendor-neutral teaching supported by current primary-source architecture, security, governance and AI guidance. These references inform learning; their inclusion does not imply endorsement or affiliation.</p></div><ul><li>Microsoft Learn / Well-Architected</li><li>NIST AI Risk Management Framework</li><li>AWS Well-Architected</li><li>Google Cloud Architecture Center</li></ul></section>
      <section className="home-section about-section" id="about"><p className="home-eyebrow">Why Architecting AI?</p><h2>Move beyond isolated AI features.</h2><p>Architecting AI helps technology professionals understand how AI systems are designed, integrated, secured, governed and operated in the enterprise.</p><Link className="home-button primary" href="/workshops">Explore Workshops <span aria-hidden="true">→</span></Link></section>
    </main>
    <footer className="public-footer"><div><Brand /><p>Enterprise AI architecture learning for technology professionals.</p></div><nav aria-label="Footer navigation"><a href="#top">Home</a><a href="#learning-journey">Learning Journey</a><Link href="/workshops">Workshops</Link><Link href="/experience/mission-zero">Mission Zero</Link><a href="#resources">Resources</a><a href="#about">About</a><Link href="/login">Login</Link><Link href="/register">Register</Link></nav><p>© {new Date().getFullYear()} Architecting AI</p></footer>
  </div>;
}
