"use client";

import Link from "next/link";
import { useState } from "react";
import { ArchitectingAiIcon, type ArchitectingAiSymbolName } from "@/components/icons";
import { publishedCurriculumLessons, type CurriculumLessonMetadata } from "@/modules/learning-experience/data/curriculum-catalog";

const labRoute = "/workshops/enterprise-ai-foundations/demo-learning-experience";
const curriculum = [
  { part: "Part I", title: "Enterprise AI Architecture Foundations", lessons: publishedCurriculumLessons },
  { part: "Part II", title: "Build the Intelligence", lessons: ["Foundation Models, Prompting & Context Engineering", "Enterprise Data for AI", "Embeddings, Vector Search & RAG", "Agents, Tools & AI Orchestration", "Enterprise Integration & APIs", "Identity, Security & AI Guardrails", "AI Governance, Risk & Responsible AI", "Observability, LLMOps & Production Operations"].map((title) => ({ title, status: "coming-soon" as const })) },
  { part: "Part III", title: "Architect the Enterprise", lessons: ["Designing an End-to-End Enterprise RAG Architecture", "Designing Enterprise Agentic AI Architecture", "Architecture Patterns, Trade-offs & Technology Decisions", "Scaling Enterprise AI: Platform Architecture", "Enterprise AI Architecture Capstone"].map((title) => ({ title, status: "coming-soon" as const })) },
];

function Brand() { return <Link className="home-brand" href="/" aria-label="Architecting AI home"><span className="home-brand-mark" aria-hidden="true">A</span><span>Architecting AI</span></Link>; }

function ArchitectureVisual() {
  const domains: { label: string; icon: ArchitectingAiSymbolName }[] = [{ label:"Business Outcomes", icon:"business-outcome" }, { label:"Enterprise Data", icon:"enterprise-data" }, { label:"AI & Intelligence", icon:"ai-intelligence" }, { label:"Integration", icon:"integration-api" }, { label:"Security & Governance", icon:"security" }, { label:"Observability & Operations", icon:"observability" }];
  return <figure className="hero-architecture" aria-labelledby="architecture-caption"><div className="architecture-network" aria-hidden="true"><div className="perspective-grid" /><div className="architecture-connectors">{domains.map((domain,index) => <i className={`domain-connector domain-connector-${index+1}`} key={domain.label} />)}</div><div className="architecture-core">{["Operations", "Integration", "Enterprise Data", "Orchestration", "AI"].map((label,index) => <div className={`stack-layer stack-layer-${index+1}`} key={label}><span>{label}</span></div>)}</div>{domains.map((domain,index) => <div className={`domain-node domain-node-${index+1}`} key={domain.label}><b className="domain-icon"><ArchitectingAiIcon name={domain.icon} size={25} /></b><span>{domain.label}</span></div>)}</div><figcaption id="architecture-caption">A learning model for reasoning about connected enterprise concerns — not a mandatory technology stack.</figcaption></figure>;
}

function RegistrationTicker() {
  const ticker = <><strong>Free registration</strong> to take assessment <i aria-hidden="true">•</i> <strong>Certificate of completion</strong> on successful assessment <i aria-hidden="true">•</i> Showcase your achievement <i aria-hidden="true">•</i> Keep learning. Keep advancing.</>;
  return <section className="registration-ticker" aria-label="Assessment registration and certificate information"><p className="sr-only">Learning content can be explored without registration. Free registration is required before the formal assessment. A certificate of completion is available after successful assessment. Showcase your achievement. Keep learning. Keep advancing.</p><div className="ticker-track" aria-hidden="true"><span>{ticker}</span><span>{ticker}</span></div></section>;
}

function DifferentiationSection() {
  const stages = [
    { id: "think", title: "THINK", subtitle: "Understand the problem", copy: <>Clarify business outcomes,<br />requirements, constraints<br />and success measures.</> },
    { id: "design", title: "DESIGN", subtitle: "Shape the architecture", copy: <>Design complete enterprise AI<br />systems that connect AI, data,<br />systems, security and operations.</> },
    { id: "decide", title: "DECIDE", subtitle: "Evaluate and defend", copy: <>Evaluate trade-offs, manage<br />risks and defend architecture<br />decisions with confidence.</> },
  ] as const;
  return <section className="differentiation-section" aria-labelledby="differentiation-title"><div className="differentiation-inner"><header><p className="home-eyebrow">What makes Architecting AI different?</p><h2 id="differentiation-title">Learn to <span>THINK</span>, <span>DESIGN</span> and <span>DECIDE</span> like an Enterprise AI Architect.</h2></header><div className="learning-model">{stages.map((stage) => <article className={`learning-model-stage is-${stage.id}`} key={stage.id}><div className="learning-model-icon"><ArchitectingAiIcon name={stage.id} size={27} /></div><h3>{stage.title}</h3><strong>{stage.subtitle}</strong><p>{stage.copy}</p><span className="learning-model-arrow" aria-hidden="true">→</span></article>)}<article className="architect-outcome"><div className="learning-model-icon"><ArchitectingAiIcon name="architecture" size={27} /></div><h3>Enterprise AI Architect</h3><p>Business <i>•</i> AI <i>•</i> Data <i>•</i> Integration<br />Security <i>•</i> Governance <i>•</i> Operations<br />Cost <i>•</i> Reliability <i>•</i> Compliance</p><strong>Deliver real business value.</strong></article></div><ul className="capability-strip" aria-label="Learning capabilities"><li><ArchitectingAiIcon name="business-outcome" size={18} />Real enterprise scenarios</li><li><ArchitectingAiIcon name="lab" size={18} />Architecture labs</li><li><ArchitectingAiIcon name="decide" size={18} />Decision challenges</li><li><ArchitectingAiIcon name="trade-off" size={18} />Trade-offs</li><li><ArchitectingAiIcon name="complete" size={18} />Best practices</li></ul></div></section>;
}

function LessonCard({ lesson }: { lesson: CurriculumLessonMetadata }) {
  const lessonIcons: ArchitectingAiSymbolName[] = ["architecture", "think", "ai-intelligence"];
  const content = <><div className="lesson-meta"><span>Lesson {lesson.number}</span><span className="status active">Available</span></div><div className={`lesson-icon lesson-icon-${lesson.number}`}><ArchitectingAiIcon name={lessonIcons[lesson.number - 1]} size={22} /></div><h3>{lesson.title}</h3><p>{lesson.description}</p><div className="lesson-card-footer"><span>Available</span><small>{lesson.experienceCount} Experiences</small></div></>;
  return <Link className="journey-card" href={lesson.href}>{content}</Link>;
}

export function PublicHomepage() {
  const [expanded, setExpanded] = useState(false);
  const toggle = () => setExpanded((value) => !value);
  const controlLabel = expanded ? "Collapse 16-lesson learning journey" : "Show all 16 lessons";
  return <div className="public-home" id="top">
    <header className="public-header"><Brand /><nav aria-label="Primary navigation"><a href="#learning-journey">Learning Journey</a><Link href={labRoute}>Architecture Lab</Link><a href="#resources">Resources</a><a href="#about">About</a></nav><Link className="header-sign-in" href="/login"><ArchitectingAiIcon name="identity" size={16} /> Sign In</Link></header>
    <RegistrationTicker />
    <main>
      <section className="home-hero"><div className="hero-inner"><div className="hero-copy"><p className="home-eyebrow">Enterprise AI Learning Studio</p><h1>Architecting AI</h1><p className="hero-lede">Master the art and science of designing, building, and operating enterprise AI solutions that deliver real business value.</p><div className="value-grid">{([{ icon:"learning-progress", title:"16-Lesson Learning Journey", copy:"A growing curriculum from foundations to advanced architectural patterns" },{ icon:"lab", title:"Hands-on Architecture Labs", copy:"Apply concepts with practical exercises and scenarios" },{ icon:"architecture", title:"Enterprise Focused", copy:"Learn principles, trade-offs and sound practices" }] as { icon: ArchitectingAiSymbolName; title: string; copy: string }[]).map((item) => <div className="hero-value" key={item.title}><span><ArchitectingAiIcon name={item.icon} size={21} /></span><div><strong>{item.title}</strong><p>{item.copy}</p></div></div>)}</div><div className="hero-actions"><Link className="home-button primary" href="/workshops/enterprise-ai-foundations">Start Learning <span aria-hidden="true">→</span></Link><Link className="home-button secondary-dark" href={labRoute}>Explore Architecture Lab <ArchitectingAiIcon name="lab" size={16} /></Link></div></div><ArchitectureVisual /></div></section>
      <DifferentiationSection />
      <section className="home-section journey-section" id="learning-journey"><div className="journey-layout"><div className="journey-intro"><p className="home-eyebrow">The curriculum</p><h2>Your Learning Journey</h2><p>A structured path from understanding AI solutions to architecting enterprise-ready AI systems.</p><div className="journey-controls"><button className="text-control" type="button" onClick={toggle} aria-expanded={expanded} aria-controls="complete-curriculum">{expanded ? "Collapse Learning Journey" : "View Full Learning Journey"} <span aria-hidden="true">{expanded ? "↑" : "→"}</span></button><button className="journey-expander" type="button" onClick={toggle} aria-expanded={expanded} aria-controls="complete-curriculum" aria-label={controlLabel}><span aria-hidden="true">{expanded ? "−" : "+"}</span><b>{expanded ? "Collapse learning journey" : "Explore all 16 lessons"}</b></button></div><Link className="workshops-context-link" href="/workshops">Explore Workshops <span aria-hidden="true">→</span></Link></div>{!expanded && <div className="journey-preview">{publishedCurriculumLessons.map((lesson) => <LessonCard key={lesson.slug} lesson={lesson} />)}</div>}</div>
        <div id="complete-curriculum" className={`complete-curriculum ${expanded ? "is-expanded" : ""}`} aria-hidden={!expanded}>{expanded && curriculum.map((group, groupIndex) => { const start = curriculum.slice(0,groupIndex).reduce((sum,item) => sum + item.lessons.length,0); return <section className="curriculum-part" key={group.part}><header><span>{group.part}</span><h3>{group.title}</h3></header><div className="curriculum-list">{group.lessons.map((lesson,index) => { const number=start+index+1; return <div className="curriculum-row" key={lesson.title}><span>{String(number).padStart(2,"0")}</span><div><strong>{lesson.title}</strong><small>{lesson.status === "available" ? `${lesson.experienceCount} Experiences · Available` : "Coming Soon"}</small></div>{"href" in lesson && <Link href={lesson.href} aria-label={`Open Lesson ${number}: ${lesson.title}`}>Open <span aria-hidden="true">→</span></Link>}</div>})}</div></section>})}</div>
      </section>
      <section className="principles-section"><div className="principles-heading"><p className="home-eyebrow">How you will learn</p><h2>Built for architecture practice</h2></div><div className="principles-grid">{[["01","Enterprise Focused","Real-world scenarios and enterprise-grade architecture thinking."],["02","Hands-on Learning","Architecture labs, decisions and exercises reinforce concepts."],["03","Vendor Neutral","Principles and trade-offs that apply across platforms."],["04","Source-Informed","Theory checked against authoritative primary guidance."]].map(([number,title,copy]) => <article key={title}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
      <section className="mission-callout"><div><p className="home-eyebrow">A three-minute introduction</p><h2>Experience Architecting AI</h2><p>Try a short interactive architecture workshop before creating an account.</p><div className="mission-reassurance">3 Minutes <span>•</span> Interactive <span>•</span> No Registration Required</div></div><Link className="home-button primary" href="/experience/mission-zero">Experience Mission Zero <span aria-hidden="true">→</span></Link></section>
      <section className="reference-band" id="resources"><div><p className="home-eyebrow">Reference sources</p><h2>Authoritative References</h2><p>The curriculum uses vendor-neutral teaching supported by current primary-source architecture, security, governance and AI guidance. These references inform learning; their inclusion does not imply endorsement or affiliation.</p></div><ul><li>Microsoft Learn / Well-Architected</li><li>NIST AI Risk Management Framework</li><li>AWS Well-Architected</li><li>Google Cloud Architecture Center</li></ul></section>
      <section className="home-section about-section" id="about"><p className="home-eyebrow">Why Architecting AI?</p><h2>Move beyond isolated AI features.</h2><p>Architecting AI helps technology professionals understand how AI systems are designed, integrated, secured, governed and operated in the enterprise.</p><Link className="home-button primary" href="/workshops">Explore Workshops <span aria-hidden="true">→</span></Link></section>
    </main>
    <footer className="public-footer"><div><Brand /><p>Enterprise AI architecture learning for technology professionals.</p></div><nav aria-label="Footer navigation"><a href="#top">Home</a><a href="#learning-journey">Learning Journey</a><Link href="/workshops">Workshops</Link><Link href="/experience/mission-zero">Mission Zero</Link><a href="#resources">Resources</a><a href="#about">About</a><Link href="/login">Login</Link><Link href="/register">Register</Link></nav><p>© {new Date().getFullYear()} Architecting AI</p></footer>
  </div>;
}
