import { publishedCurriculumLessons } from "@/modules/learning-experience/data/curriculum-catalog";
export type CourseStatus = "available" | "coming-soon";
export interface CourseLesson { number:number; title:string; description?:string; status:CourseStatus; href?:string }
export interface Course { slug:string; title:string; shortTitle:string; audience:string; level:string; status:CourseStatus; lessonCount:number; summary:string; eyebrow:string; accent:"teal"|"violet"|"blue"|"amber"; href:string; lessons?:CourseLesson[] }
const kids=["Meet Artificial Intelligence","How Do Machines Learn?","How AI Sees Pictures","Talking to AI: The Magic of Prompts","Create Your Own AI Storybook","AI Art and Creativity","Build Your First Chatbot — No Coding","Play and Learn with AI","Make AI Talk","Become an AI Detective","My AI Creative Project","AI Fun Challenge and Showcase"];
const planned=["Enterprise Data for AI","Embeddings, Vector Search & RAG","Agents, Tools & AI Orchestration","Enterprise Integration & APIs","Identity, Security & AI Guardrails","AI Governance, Risk & Responsible AI","Observability, LLMOps & Production Operations","Designing an End-to-End Enterprise RAG Architecture","Designing Enterprise Agentic AI Architecture","Architecture Patterns, Trade-offs & Technology Decisions","Scaling Enterprise AI: Platform Architecture","Enterprise AI Architecture Capstone"];
export const architectLessons:CourseLesson[]=[...publishedCurriculumLessons.map(l=>({number:l.number,title:l.title,description:l.description,status:l.status,href:l.href})),...planned.map((title,index)=>({number:index+5,title,status:"coming-soon" as const}))];
export const courses:Course[]=[
{slug:"ai-for-kids",title:"AI for Kids — Imagine, Create & Discover",shortTitle:"AI for Kids",audience:"Ages 10–15",level:"Beginner",status:"coming-soon",lessonCount:12,summary:"A creative, project-led introduction to how AI works and how young learners can use it thoughtfully.",eyebrow:"Flagship course",accent:"teal",href:"/courses/ai-for-kids",lessons:kids.map((title,index)=>({number:index+1,title,status:"coming-soon"}))},
{slug:"ai-architect",title:"AI Architect",shortTitle:"AI Architect",audience:"Professionals",level:"Advanced",status:"available",lessonCount:16,summary:"Design secure, governed and production-ready enterprise AI systems through structured lessons and architecture labs.",eyebrow:"Professional learning path",accent:"violet",href:"/courses/ai-architect",lessons:architectLessons},
{slug:"ai-agents-automation",title:"AI Agents & Automation",shortTitle:"AI Agents & Automation",audience:"Professionals",level:"Intermediate",status:"coming-soon",lessonCount:0,summary:"Learn to design useful agent workflows, tool integrations and dependable automation.",eyebrow:"Coming soon",accent:"blue",href:"/courses/ai-agents-automation"},
{slug:"cybersecurity-essentials",title:"Cybersecurity Essentials",shortTitle:"Cybersecurity Essentials",audience:"Learners & professionals",level:"Beginner",status:"coming-soon",lessonCount:0,summary:"Build practical foundations for safer digital systems, decisions and everyday technology use.",eyebrow:"Coming soon",accent:"amber",href:"/courses/cybersecurity-essentials"}];
export const getCourse=(slug:string)=>courses.find(c=>c.slug===slug);
