"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { CompactArchitecturePath } from "@/modules/architecture-explorer/components/compact-architecture-path";
import { EnterpriseArchitectureExplorer } from "@/modules/architecture-explorer/components/enterprise-architecture-explorer";
import { applyDecisionFeedback, applyDecisionOptions, cioDecisionFeedback, cioDecisionOptions, getDecisionLabel, thinkingLensLayers } from "../mission-zero-content";
import type { MissionZeroState } from "../types";

const initialState: MissionZeroState = { currentStage: 1, selectedCioDecision: null, selectedArchitectureDomain: null, selectedApplyDecision: null };

export function MissionZeroExperience() {
  const [missionState, setMissionState] = useState(initialState);
  const stageRef = useRef<HTMLElement>(null);
  const goToStage = (currentStage: MissionZeroState["currentStage"]) => setMissionState((state) => ({ ...state, currentStage }));

  useEffect(() => { if (missionState.currentStage > 1) stageRef.current?.querySelector<HTMLElement>("h1")?.focus(); }, [missionState.currentStage]);

  return <section ref={stageRef} className={`mission-stage mission-stage-${missionState.currentStage}`} aria-labelledby={`stage-${missionState.currentStage}-title`}>
    {missionState.currentStage === 1 && <div className="welcome-stage stage-enter"><p className="mission-label">Mission Zero</p><h1 id="stage-1-title">How Enterprise AI<br />Architects Think</h1><p className="stage-lede">A 3-minute interactive experience in architectural thinking.</p><button className="primary-button" onClick={() => goToStage(2)}>Start Experience <span aria-hidden="true">&rarr;</span></button><p className="reassurance"><span>3 Minutes</span><span>Interactive</span><span>No Registration Required</span></p></div>}

    {missionState.currentStage === 2 && <div className="challenge-stage stage-enter"><StageHeader step={2} label="Enterprise challenge" /><div className="challenge-grid"><div><h1 id="stage-2-title" tabIndex={-1}>Your CIO asks:</h1><blockquote>&ldquo;We want to introduce AI into our organization.<br />Where should we start?&rdquo;</blockquote></div><div><DecisionChoices name="cio-decision" legend="Choose the strongest starting point" options={cioDecisionOptions} selectedId={missionState.selectedCioDecision} onSelect={(selectedCioDecision) => setMissionState((state) => ({ ...state, selectedCioDecision }))} /><button className="primary-button continue-button" disabled={!missionState.selectedCioDecision} onClick={() => goToStage(3)}>Continue <span aria-hidden="true">&rarr;</span></button></div></div></div>}

    {missionState.currentStage === 3 && <div className="lens-stage stage-enter"><StageHeader step={3} label="Architecture thinking lens" /><div className="lens-intro"><div><p className="eyebrow">Shift the starting point</p><h1 id="stage-3-title" tabIndex={-1}>See the whole enterprise system.</h1></div><p>Architecture is a lens for making connected decisions&mdash;not a rigid sequence of technology steps.</p></div><div className="thinking-lens" aria-label="Architecture thinking lens"><div className="lens-flow">{thinkingLensLayers.map((layer, index) => <div className="lens-item" key={layer}><span className="lens-index">0{index + 1}</span><strong>{layer}</strong>{index < thinkingLensLayers.length - 1 && <span className="lens-arrow" aria-hidden="true">&darr;</span>}</div>)}</div><div className="lens-cross"><div><span>Cross-cutting</span><strong>Identity / Security / Governance</strong></div><div><span>Foundation</span><strong>Observability / Operations / Cost</strong></div></div></div><div className="insight-callout"><span className="insight-mark" aria-hidden="true">&crarr;</span><p><strong>Enterprise AI begins with business context.</strong><br />Technology is an enabler&mdash;not the starting point.</p><button className="text-button" onClick={() => goToStage(4)}>Explore the Architecture <span aria-hidden="true">&rarr;</span></button></div></div>}

    {missionState.currentStage === 4 && <div className="explorer-stage stage-enter"><StageHeader step={4} label="Architecture explorer" /><div className="explorer-heading"><div><p className="eyebrow">Enterprise AI Architecture Explorer</p><h1 id="stage-4-title" tabIndex={-1}>Explore how the system connects.</h1></div><p>Select a domain to reveal the decisions and relationships it influences.</p></div><EnterpriseArchitectureExplorer selectedDomainId={missionState.selectedArchitectureDomain} onSelectedDomainChange={(selectedArchitectureDomain) => setMissionState((state) => ({ ...state, selectedArchitectureDomain }))} /><div className="stage-action"><button className="primary-button" onClick={() => goToStage(5)}>Apply What You Learned <span aria-hidden="true">&rarr;</span></button></div></div>}

    {missionState.currentStage === 5 && <div className="apply-stage stage-enter"><StageHeader step={5} label="Apply" /><div className="apply-layout"><div className="apply-prompt"><p className="eyebrow">A second enterprise scenario</p><h1 id="stage-5-title" tabIndex={-1}>Apply the architecture lens.</h1><blockquote>&ldquo;Your organization wants an AI assistant that answers employees&apos; HR policy questions.&rdquo;</blockquote><h2>Before choosing the model or AI platform, what should the architect establish first?</h2></div><div><DecisionChoices name="apply-decision" legend="Choose your architectural starting point" options={applyDecisionOptions} selectedId={missionState.selectedApplyDecision} onSelect={(selectedApplyDecision) => setMissionState((state) => ({ ...state, selectedApplyDecision }))} lighter />{missionState.selectedApplyDecision && <div className="preview-reveal"><p className="preview-label">Keep the connected system in view</p><CompactArchitecturePath compact /></div>}<button className="primary-button continue-button" disabled={!missionState.selectedApplyDecision} onClick={() => goToStage(6)}>Continue to Architect Insight <span aria-hidden="true">&rarr;</span></button></div></div></div>}

    {missionState.currentStage === 6 && <div className="insight-stage stage-enter"><StageHeader step={6} label="Architect insight" /><div className="insight-heading"><p className="eyebrow">Architect Insight</p><h1 id="stage-6-title" tabIndex={-1}>Enterprise AI starts with the business problem&mdash;not the model.</h1></div><div className="reflection-grid" aria-label="Reflection on your two decisions"><ReflectionCard index="01" title="Your first decision" choice={getDecisionLabel(cioDecisionOptions, missionState.selectedCioDecision)} feedback={cioDecisionFeedback[missionState.selectedCioDecision ?? ""]} /><ReflectionCard index="02" title="Your second decision" choice={getDecisionLabel(applyDecisionOptions, missionState.selectedApplyDecision)} feedback={applyDecisionFeedback[missionState.selectedApplyDecision ?? ""]} /></div><CompactArchitecturePath /><div className="stage-action"><button className="primary-button" onClick={() => goToStage(7)}>Complete Mission <span aria-hidden="true">&rarr;</span></button></div></div>}

    {missionState.currentStage === 7 && <div className="complete-stage stage-enter"><StageHeader step={7} label="Mission complete" /><div className="complete-content"><p className="mission-label">Mission Zero Complete</p><h1 id="stage-7-title" tabIndex={-1}>You just experienced how Enterprise AI Architects think.</h1><ul className="outcome-list"><li>You challenged a technology-first assumption.</li><li>You explored an Enterprise AI architecture.</li><li>You discovered how business, AI, data, security and operations connect.</li><li>You applied architectural thinking to a realistic enterprise scenario.</li></ul><div className="next-step"><p className="eyebrow">Ready to go deeper?</p><h2>Continue with Enterprise AI Foundations.</h2><p>Build these concepts into complete enterprise architecture decisions.</p><div className="completion-actions"><Link className="primary-button button-link" href="/register">Create Free Account</Link><Link className="secondary-button" href="/workshops">Explore Workshops</Link></div><Link className="home-link" href="/">Back to Home</Link></div></div></div>}
  </section>;
}

function StageHeader({ step, label }: { step: number; label: string }) { return <div className="stage-header"><span>{label}</span><span>Mission Zero &middot; Step {step} of 7</span></div>; }

function DecisionChoices({ name, legend, options, selectedId, onSelect, lighter = false }: { name: string; legend: string; options: readonly { id: string; label: string }[]; selectedId: string | null; onSelect: (id: string) => void; lighter?: boolean }) {
  return <fieldset className={lighter ? "decision-fieldset is-light" : "decision-fieldset"}><legend>{legend}</legend>{options.map((option, index) => <label key={option.id} className={`decision-option ${selectedId === option.id ? "is-selected" : ""}`}><input type="radio" name={name} value={option.id} checked={selectedId === option.id} onChange={() => onSelect(option.id)} /><span className="option-letter">{String.fromCharCode(65 + index)}</span><span>{option.label}</span>{selectedId === option.id && <span className="choice-selected">Selected</span>}</label>)}</fieldset>;
}

function ReflectionCard({ index, title, choice, feedback }: { index: string; title: string; choice: string; feedback?: string }) {
  return <article className="reflection-card"><div className="reflection-number">{index}</div><p className="reflection-label">{title}</p><h2>{choice}</h2><p>{feedback ?? "This decision is part of the architecture conversation. An architect connects it back to value, users and constraints."}</p></article>;
}
